#define ATTENTION_DROPOUT 0.0
#define BOS_TOKEN_ID 50256
#define EMBD_DROPOUT 0.0
#define EOS_TOKEN_ID 50256
#define HEAD_DIM 80 // HIDDEN_SIZE / NUM_ATTENTION_HEADS
#define HIDDEN_ACT_GELU_NEW // 使用特殊處理
#define HIDDEN_SIZE 2560
#define INITIALIZER_RANGE 0.02
#define INTERMEDIATE_SIZE 10240
#define LAYER_NORM_EPS 1e-05
#define MAX_POSITION_EMBEDDINGS 2048
#define MODEL_TYPE_PHI // 使用特殊處理
#define NUM_ATTENTION_HEADS 32
#define NUM_HIDDEN_LAYERS 32
#define NUM_KEY_VALUE_GROUPS 1 // NUM_ATTENTION_HEADS / NUM_KEY_VALUE_HEADS
#define NUM_KEY_VALUE_HEADS 32
#define PARTIAL_ROTARY_FACTOR 0.4
#define QK_LAYERNORM false
#define RESID_DROPOUT 0.1
#define ROPE_SCALING null
#define ROPE_THETA 10000.0
#define ROTARY_DIM 32 // HEAD_DIM * PARTIAL_ROTARY_FACTOR
#define TIE_WORD_EMBEDDINGS false
#define TORCH_DTYPE_FLOAT16 // 使用特殊處理
#define TRANSFORMERS_VERSION_4_37_0 // 使用特殊處理
#define USE_CACHE true
#define VOCAB_SIZE 51200