// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module attention_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        qk_scaled_1_reload,
        qk_scaled_reload,
        qk_scaled_3_reload,
        qk_scaled_2_reload,
        qk_scaled_exp_3_out,
        qk_scaled_exp_3_out_ap_vld,
        qk_scaled_exp_2_out,
        qk_scaled_exp_2_out_ap_vld,
        qk_scaled_exp_1_out,
        qk_scaled_exp_1_out_ap_vld,
        qk_scaled_exp_out,
        qk_scaled_exp_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] qk_scaled_1_reload;
input  [31:0] qk_scaled_reload;
input  [31:0] qk_scaled_3_reload;
input  [31:0] qk_scaled_2_reload;
output  [31:0] qk_scaled_exp_3_out;
output   qk_scaled_exp_3_out_ap_vld;
output  [31:0] qk_scaled_exp_2_out;
output   qk_scaled_exp_2_out_ap_vld;
output  [31:0] qk_scaled_exp_1_out;
output   qk_scaled_exp_1_out_ap_vld;
output  [31:0] qk_scaled_exp_out;
output   qk_scaled_exp_out_ap_vld;

reg ap_idle;
reg qk_scaled_exp_3_out_ap_vld;
reg qk_scaled_exp_2_out_ap_vld;
reg qk_scaled_exp_1_out_ap_vld;
reg qk_scaled_exp_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln31_fu_186_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln31_reg_596;
reg   [0:0] icmp_ln31_reg_596_pp0_iter1_reg;
reg   [0:0] icmp_ln31_reg_596_pp0_iter2_reg;
reg   [0:0] icmp_ln31_reg_596_pp0_iter3_reg;
reg   [0:0] icmp_ln31_reg_596_pp0_iter4_reg;
reg   [0:0] icmp_ln31_reg_596_pp0_iter5_reg;
reg   [0:0] icmp_ln31_reg_596_pp0_iter6_reg;
reg   [0:0] icmp_ln31_reg_596_pp0_iter7_reg;
reg   [0:0] icmp_ln31_reg_596_pp0_iter8_reg;
reg   [0:0] icmp_ln31_reg_596_pp0_iter9_reg;
reg   [0:0] icmp_ln31_reg_596_pp0_iter10_reg;
reg   [0:0] icmp_ln31_reg_596_pp0_iter11_reg;
reg   [0:0] icmp_ln31_reg_596_pp0_iter12_reg;
reg   [0:0] icmp_ln31_reg_596_pp0_iter13_reg;
reg   [0:0] icmp_ln31_reg_596_pp0_iter14_reg;
reg   [0:0] icmp_ln31_reg_596_pp0_iter15_reg;
reg   [0:0] icmp_ln31_reg_596_pp0_iter16_reg;
reg   [0:0] icmp_ln31_reg_596_pp0_iter17_reg;
reg   [0:0] icmp_ln31_reg_596_pp0_iter18_reg;
reg   [0:0] icmp_ln31_reg_596_pp0_iter19_reg;
reg   [0:0] icmp_ln31_reg_596_pp0_iter20_reg;
reg   [0:0] icmp_ln31_reg_596_pp0_iter21_reg;
reg   [0:0] icmp_ln31_reg_596_pp0_iter22_reg;
reg   [0:0] icmp_ln31_reg_596_pp0_iter23_reg;
reg   [0:0] icmp_ln31_reg_596_pp0_iter24_reg;
wire   [0:0] cond60_fu_240_p2;
reg   [0:0] cond60_reg_600;
reg   [0:0] cond60_reg_600_pp0_iter1_reg;
reg   [0:0] cond60_reg_600_pp0_iter2_reg;
reg   [0:0] cond60_reg_600_pp0_iter3_reg;
reg   [0:0] cond60_reg_600_pp0_iter4_reg;
reg   [0:0] cond60_reg_600_pp0_iter5_reg;
reg   [0:0] cond60_reg_600_pp0_iter6_reg;
reg   [0:0] cond60_reg_600_pp0_iter7_reg;
reg   [0:0] cond60_reg_600_pp0_iter8_reg;
reg   [0:0] cond60_reg_600_pp0_iter9_reg;
reg   [0:0] cond60_reg_600_pp0_iter10_reg;
reg   [0:0] cond60_reg_600_pp0_iter11_reg;
reg   [0:0] cond60_reg_600_pp0_iter12_reg;
reg   [0:0] cond60_reg_600_pp0_iter13_reg;
reg   [0:0] cond60_reg_600_pp0_iter14_reg;
reg   [0:0] cond60_reg_600_pp0_iter15_reg;
reg   [0:0] cond60_reg_600_pp0_iter16_reg;
reg   [0:0] cond60_reg_600_pp0_iter17_reg;
reg   [0:0] cond60_reg_600_pp0_iter18_reg;
reg   [0:0] cond60_reg_600_pp0_iter19_reg;
reg   [0:0] cond60_reg_600_pp0_iter20_reg;
reg   [0:0] cond60_reg_600_pp0_iter21_reg;
reg   [0:0] cond60_reg_600_pp0_iter22_reg;
reg   [0:0] cond60_reg_600_pp0_iter23_reg;
reg   [0:0] cond60_reg_600_pp0_iter24_reg;
reg   [0:0] cond60_reg_600_pp0_iter25_reg;
wire   [31:0] select_ln33_6_fu_268_p3;
reg   [31:0] select_ln33_6_reg_608;
wire   [0:0] or_ln33_fu_282_p2;
reg   [0:0] or_ln33_reg_613;
reg   [0:0] or_ln33_reg_613_pp0_iter1_reg;
reg   [0:0] or_ln33_reg_613_pp0_iter2_reg;
reg   [0:0] or_ln33_reg_613_pp0_iter3_reg;
reg   [0:0] or_ln33_reg_613_pp0_iter4_reg;
reg   [0:0] or_ln33_reg_613_pp0_iter5_reg;
reg   [0:0] or_ln33_reg_613_pp0_iter6_reg;
reg   [0:0] or_ln33_reg_613_pp0_iter7_reg;
reg   [0:0] or_ln33_reg_613_pp0_iter8_reg;
reg   [0:0] or_ln33_reg_613_pp0_iter9_reg;
reg   [0:0] or_ln33_reg_613_pp0_iter10_reg;
reg   [0:0] or_ln33_reg_613_pp0_iter11_reg;
reg   [0:0] or_ln33_reg_613_pp0_iter12_reg;
reg   [0:0] or_ln33_reg_613_pp0_iter13_reg;
reg   [0:0] or_ln33_reg_613_pp0_iter14_reg;
reg   [0:0] or_ln33_reg_613_pp0_iter15_reg;
reg   [0:0] or_ln33_reg_613_pp0_iter16_reg;
reg   [0:0] or_ln33_reg_613_pp0_iter17_reg;
reg   [0:0] or_ln33_reg_613_pp0_iter18_reg;
reg   [0:0] or_ln33_reg_613_pp0_iter19_reg;
reg   [0:0] or_ln33_reg_613_pp0_iter20_reg;
reg   [0:0] or_ln33_reg_613_pp0_iter21_reg;
reg   [0:0] or_ln33_reg_613_pp0_iter22_reg;
reg   [0:0] or_ln33_reg_613_pp0_iter23_reg;
reg   [0:0] or_ln33_reg_613_pp0_iter24_reg;
reg   [0:0] or_ln33_reg_613_pp0_iter25_reg;
wire   [63:0] grp_fu_160_p1;
reg   [63:0] conv_reg_621;
wire   [63:0] grp_fu_163_p2;
reg   [63:0] dc_reg_626;
reg   [0:0] xs_sign_reg_631;
wire   [31:0] val_fu_424_p3;
reg   [31:0] val_reg_636;
reg   [1:0] j_fu_80;
wire   [1:0] select_ln32_fu_288_p3;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_j_load;
wire    ap_block_pp0_stage0;
reg   [31:0] qk_scaled_exp_fu_84;
wire   [31:0] qk_scaled_exp_4_fu_504_p3;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg    ap_loop_exit_ready_pp0_iter22_reg;
reg    ap_loop_exit_ready_pp0_iter23_reg;
reg    ap_loop_exit_ready_pp0_iter24_reg;
reg    ap_loop_exit_ready_pp0_iter25_reg;
reg   [31:0] qk_scaled_exp_1_fu_88;
wire   [31:0] qk_scaled_exp_5_fu_497_p3;
reg   [31:0] qk_scaled_exp_2_fu_92;
wire   [31:0] qk_scaled_exp_6_fu_490_p3;
reg   [31:0] qk_scaled_exp_3_fu_96;
wire   [31:0] qk_scaled_exp_7_fu_483_p3;
reg   [1:0] i_fu_100;
wire   [1:0] select_ln31_fu_232_p3;
reg   [1:0] ap_sig_allocacmp_i_load;
reg   [2:0] indvar_flatten48_fu_104;
wire   [2:0] add_ln31_1_fu_192_p2;
reg   [2:0] ap_sig_allocacmp_indvar_flatten48_load;
wire    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln32_fu_214_p2;
wire   [0:0] trunc_ln31_fu_204_p1;
wire   [0:0] xor_ln30_fu_220_p2;
wire   [1:0] add_ln31_fu_208_p2;
wire   [0:0] and_ln30_fu_226_p2;
wire   [0:0] empty_fu_246_p2;
wire   [31:0] select_ln33_5_fu_260_p3;
wire   [31:0] select_ln33_4_fu_252_p3;
wire   [0:0] xor_ln33_fu_276_p2;
wire   [63:0] data_fu_311_p1;
wire   [51:0] trunc_ln505_fu_330_p1;
wire   [53:0] mantissa_fu_334_p4;
wire   [10:0] xs_exp_fu_322_p3;
wire   [11:0] zext_ln486_fu_348_p1;
wire   [11:0] add_ln486_fu_352_p2;
wire   [10:0] sub_ln18_fu_366_p2;
wire   [0:0] tmp_fu_358_p3;
wire  signed [11:0] sext_ln18_fu_372_p1;
wire   [11:0] select_ln18_fu_376_p3;
wire  signed [31:0] sext_ln18_1_fu_384_p1;
wire   [136:0] zext_ln15_fu_344_p1;
wire   [136:0] zext_ln18_fu_388_p1;
wire   [136:0] lshr_ln18_fu_392_p2;
wire   [136:0] shl_ln18_fu_398_p2;
wire   [31:0] tmp_6_fu_404_p4;
wire   [31:0] tmp_7_fu_414_p4;
wire   [31:0] result_1_fu_444_p2;
wire   [31:0] result_2_fu_449_p3;
wire   [31:0] select_ln33_2_fu_469_p3;
wire   [31:0] select_ln33_3_fu_476_p3;
wire   [31:0] select_ln33_fu_455_p3;
wire   [31:0] select_ln33_1_fu_462_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 j_fu_80 = 2'd0;
#0 qk_scaled_exp_fu_84 = 32'd0;
#0 qk_scaled_exp_1_fu_88 = 32'd0;
#0 qk_scaled_exp_2_fu_92 = 32'd0;
#0 qk_scaled_exp_3_fu_96 = 32'd0;
#0 i_fu_100 = 2'd0;
#0 indvar_flatten48_fu_104 = 3'd0;
#0 ap_done_reg = 1'b0;
end

attention_sitodp_32ns_64_4_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
sitodp_32ns_64_4_no_dsp_1_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln33_6_reg_608),
    .ce(1'b1),
    .dout(grp_fu_160_p1)
);

attention_dexp_64ns_64ns_64_20_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 20 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dexp_64ns_64ns_64_20_full_dsp_1_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(64'd0),
    .din1(conv_reg_621),
    .ce(1'b1),
    .dout(grp_fu_163_p2)
);

attention_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter25_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln31_fu_186_p2 == 1'd0))) begin
            i_fu_100 <= select_ln31_fu_232_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_100 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln31_fu_186_p2 == 1'd0))) begin
            indvar_flatten48_fu_104 <= add_ln31_1_fu_192_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten48_fu_104 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln31_fu_186_p2 == 1'd0))) begin
            j_fu_80 <= select_ln32_fu_288_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_80 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
        ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
        ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
        ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
        ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        cond60_reg_600_pp0_iter10_reg <= cond60_reg_600_pp0_iter9_reg;
        cond60_reg_600_pp0_iter11_reg <= cond60_reg_600_pp0_iter10_reg;
        cond60_reg_600_pp0_iter12_reg <= cond60_reg_600_pp0_iter11_reg;
        cond60_reg_600_pp0_iter13_reg <= cond60_reg_600_pp0_iter12_reg;
        cond60_reg_600_pp0_iter14_reg <= cond60_reg_600_pp0_iter13_reg;
        cond60_reg_600_pp0_iter15_reg <= cond60_reg_600_pp0_iter14_reg;
        cond60_reg_600_pp0_iter16_reg <= cond60_reg_600_pp0_iter15_reg;
        cond60_reg_600_pp0_iter17_reg <= cond60_reg_600_pp0_iter16_reg;
        cond60_reg_600_pp0_iter18_reg <= cond60_reg_600_pp0_iter17_reg;
        cond60_reg_600_pp0_iter19_reg <= cond60_reg_600_pp0_iter18_reg;
        cond60_reg_600_pp0_iter20_reg <= cond60_reg_600_pp0_iter19_reg;
        cond60_reg_600_pp0_iter21_reg <= cond60_reg_600_pp0_iter20_reg;
        cond60_reg_600_pp0_iter22_reg <= cond60_reg_600_pp0_iter21_reg;
        cond60_reg_600_pp0_iter23_reg <= cond60_reg_600_pp0_iter22_reg;
        cond60_reg_600_pp0_iter24_reg <= cond60_reg_600_pp0_iter23_reg;
        cond60_reg_600_pp0_iter25_reg <= cond60_reg_600_pp0_iter24_reg;
        cond60_reg_600_pp0_iter2_reg <= cond60_reg_600_pp0_iter1_reg;
        cond60_reg_600_pp0_iter3_reg <= cond60_reg_600_pp0_iter2_reg;
        cond60_reg_600_pp0_iter4_reg <= cond60_reg_600_pp0_iter3_reg;
        cond60_reg_600_pp0_iter5_reg <= cond60_reg_600_pp0_iter4_reg;
        cond60_reg_600_pp0_iter6_reg <= cond60_reg_600_pp0_iter5_reg;
        cond60_reg_600_pp0_iter7_reg <= cond60_reg_600_pp0_iter6_reg;
        cond60_reg_600_pp0_iter8_reg <= cond60_reg_600_pp0_iter7_reg;
        cond60_reg_600_pp0_iter9_reg <= cond60_reg_600_pp0_iter8_reg;
        conv_reg_621 <= grp_fu_160_p1;
        dc_reg_626 <= grp_fu_163_p2;
        icmp_ln31_reg_596_pp0_iter10_reg <= icmp_ln31_reg_596_pp0_iter9_reg;
        icmp_ln31_reg_596_pp0_iter11_reg <= icmp_ln31_reg_596_pp0_iter10_reg;
        icmp_ln31_reg_596_pp0_iter12_reg <= icmp_ln31_reg_596_pp0_iter11_reg;
        icmp_ln31_reg_596_pp0_iter13_reg <= icmp_ln31_reg_596_pp0_iter12_reg;
        icmp_ln31_reg_596_pp0_iter14_reg <= icmp_ln31_reg_596_pp0_iter13_reg;
        icmp_ln31_reg_596_pp0_iter15_reg <= icmp_ln31_reg_596_pp0_iter14_reg;
        icmp_ln31_reg_596_pp0_iter16_reg <= icmp_ln31_reg_596_pp0_iter15_reg;
        icmp_ln31_reg_596_pp0_iter17_reg <= icmp_ln31_reg_596_pp0_iter16_reg;
        icmp_ln31_reg_596_pp0_iter18_reg <= icmp_ln31_reg_596_pp0_iter17_reg;
        icmp_ln31_reg_596_pp0_iter19_reg <= icmp_ln31_reg_596_pp0_iter18_reg;
        icmp_ln31_reg_596_pp0_iter20_reg <= icmp_ln31_reg_596_pp0_iter19_reg;
        icmp_ln31_reg_596_pp0_iter21_reg <= icmp_ln31_reg_596_pp0_iter20_reg;
        icmp_ln31_reg_596_pp0_iter22_reg <= icmp_ln31_reg_596_pp0_iter21_reg;
        icmp_ln31_reg_596_pp0_iter23_reg <= icmp_ln31_reg_596_pp0_iter22_reg;
        icmp_ln31_reg_596_pp0_iter24_reg <= icmp_ln31_reg_596_pp0_iter23_reg;
        icmp_ln31_reg_596_pp0_iter2_reg <= icmp_ln31_reg_596_pp0_iter1_reg;
        icmp_ln31_reg_596_pp0_iter3_reg <= icmp_ln31_reg_596_pp0_iter2_reg;
        icmp_ln31_reg_596_pp0_iter4_reg <= icmp_ln31_reg_596_pp0_iter3_reg;
        icmp_ln31_reg_596_pp0_iter5_reg <= icmp_ln31_reg_596_pp0_iter4_reg;
        icmp_ln31_reg_596_pp0_iter6_reg <= icmp_ln31_reg_596_pp0_iter5_reg;
        icmp_ln31_reg_596_pp0_iter7_reg <= icmp_ln31_reg_596_pp0_iter6_reg;
        icmp_ln31_reg_596_pp0_iter8_reg <= icmp_ln31_reg_596_pp0_iter7_reg;
        icmp_ln31_reg_596_pp0_iter9_reg <= icmp_ln31_reg_596_pp0_iter8_reg;
        or_ln33_reg_613_pp0_iter10_reg <= or_ln33_reg_613_pp0_iter9_reg;
        or_ln33_reg_613_pp0_iter11_reg <= or_ln33_reg_613_pp0_iter10_reg;
        or_ln33_reg_613_pp0_iter12_reg <= or_ln33_reg_613_pp0_iter11_reg;
        or_ln33_reg_613_pp0_iter13_reg <= or_ln33_reg_613_pp0_iter12_reg;
        or_ln33_reg_613_pp0_iter14_reg <= or_ln33_reg_613_pp0_iter13_reg;
        or_ln33_reg_613_pp0_iter15_reg <= or_ln33_reg_613_pp0_iter14_reg;
        or_ln33_reg_613_pp0_iter16_reg <= or_ln33_reg_613_pp0_iter15_reg;
        or_ln33_reg_613_pp0_iter17_reg <= or_ln33_reg_613_pp0_iter16_reg;
        or_ln33_reg_613_pp0_iter18_reg <= or_ln33_reg_613_pp0_iter17_reg;
        or_ln33_reg_613_pp0_iter19_reg <= or_ln33_reg_613_pp0_iter18_reg;
        or_ln33_reg_613_pp0_iter20_reg <= or_ln33_reg_613_pp0_iter19_reg;
        or_ln33_reg_613_pp0_iter21_reg <= or_ln33_reg_613_pp0_iter20_reg;
        or_ln33_reg_613_pp0_iter22_reg <= or_ln33_reg_613_pp0_iter21_reg;
        or_ln33_reg_613_pp0_iter23_reg <= or_ln33_reg_613_pp0_iter22_reg;
        or_ln33_reg_613_pp0_iter24_reg <= or_ln33_reg_613_pp0_iter23_reg;
        or_ln33_reg_613_pp0_iter25_reg <= or_ln33_reg_613_pp0_iter24_reg;
        or_ln33_reg_613_pp0_iter2_reg <= or_ln33_reg_613_pp0_iter1_reg;
        or_ln33_reg_613_pp0_iter3_reg <= or_ln33_reg_613_pp0_iter2_reg;
        or_ln33_reg_613_pp0_iter4_reg <= or_ln33_reg_613_pp0_iter3_reg;
        or_ln33_reg_613_pp0_iter5_reg <= or_ln33_reg_613_pp0_iter4_reg;
        or_ln33_reg_613_pp0_iter6_reg <= or_ln33_reg_613_pp0_iter5_reg;
        or_ln33_reg_613_pp0_iter7_reg <= or_ln33_reg_613_pp0_iter6_reg;
        or_ln33_reg_613_pp0_iter8_reg <= or_ln33_reg_613_pp0_iter7_reg;
        or_ln33_reg_613_pp0_iter9_reg <= or_ln33_reg_613_pp0_iter8_reg;
        val_reg_636 <= val_fu_424_p3;
        xs_sign_reg_631 <= data_fu_311_p1[32'd63];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        cond60_reg_600 <= cond60_fu_240_p2;
        cond60_reg_600_pp0_iter1_reg <= cond60_reg_600;
        icmp_ln31_reg_596 <= icmp_ln31_fu_186_p2;
        icmp_ln31_reg_596_pp0_iter1_reg <= icmp_ln31_reg_596;
        or_ln33_reg_613 <= or_ln33_fu_282_p2;
        or_ln33_reg_613_pp0_iter1_reg <= or_ln33_reg_613;
        select_ln33_6_reg_608 <= select_ln33_6_fu_268_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        qk_scaled_exp_1_fu_88 <= qk_scaled_exp_5_fu_497_p3;
        qk_scaled_exp_2_fu_92 <= qk_scaled_exp_6_fu_490_p3;
        qk_scaled_exp_3_fu_96 <= qk_scaled_exp_7_fu_483_p3;
        qk_scaled_exp_fu_84 <= qk_scaled_exp_4_fu_504_p3;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln31_fu_186_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter25_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_idle_pp0 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_i_load = 2'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_100;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten48_load = 3'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten48_load = indvar_flatten48_fu_104;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_j_load = 2'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_80;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter25_reg == 1'b1) & (icmp_ln31_reg_596_pp0_iter24_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        qk_scaled_exp_1_out_ap_vld = 1'b1;
    end else begin
        qk_scaled_exp_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter25_reg == 1'b1) & (icmp_ln31_reg_596_pp0_iter24_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        qk_scaled_exp_2_out_ap_vld = 1'b1;
    end else begin
        qk_scaled_exp_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter25_reg == 1'b1) & (icmp_ln31_reg_596_pp0_iter24_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        qk_scaled_exp_3_out_ap_vld = 1'b1;
    end else begin
        qk_scaled_exp_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter25_reg == 1'b1) & (icmp_ln31_reg_596_pp0_iter24_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        qk_scaled_exp_out_ap_vld = 1'b1;
    end else begin
        qk_scaled_exp_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln31_1_fu_192_p2 = (ap_sig_allocacmp_indvar_flatten48_load + 3'd1);

assign add_ln31_fu_208_p2 = (ap_sig_allocacmp_i_load + 2'd1);

assign add_ln486_fu_352_p2 = ($signed(zext_ln486_fu_348_p1) + $signed(12'd3073));

assign and_ln30_fu_226_p2 = (xor_ln30_fu_220_p2 & trunc_ln31_fu_204_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign cond60_fu_240_p2 = ((select_ln31_fu_232_p3 == 2'd0) ? 1'b1 : 1'b0);

assign data_fu_311_p1 = dc_reg_626;

assign empty_fu_246_p2 = ((select_ln31_fu_232_p3 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln31_fu_186_p2 = ((ap_sig_allocacmp_indvar_flatten48_load == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln32_fu_214_p2 = ((ap_sig_allocacmp_j_load == 2'd2) ? 1'b1 : 1'b0);

assign lshr_ln18_fu_392_p2 = zext_ln15_fu_344_p1 >> zext_ln18_fu_388_p1;

assign mantissa_fu_334_p4 = {{{{1'd1}, {trunc_ln505_fu_330_p1}}}, {1'd0}};

assign or_ln33_fu_282_p2 = (xor_ln33_fu_276_p2 | icmp_ln32_fu_214_p2);

assign qk_scaled_exp_1_out = qk_scaled_exp_1_fu_88;

assign qk_scaled_exp_2_out = qk_scaled_exp_2_fu_92;

assign qk_scaled_exp_3_out = qk_scaled_exp_3_fu_96;

assign qk_scaled_exp_4_fu_504_p3 = ((cond60_reg_600_pp0_iter25_reg[0:0] == 1'b1) ? select_ln33_1_fu_462_p3 : qk_scaled_exp_fu_84);

assign qk_scaled_exp_5_fu_497_p3 = ((cond60_reg_600_pp0_iter25_reg[0:0] == 1'b1) ? select_ln33_fu_455_p3 : qk_scaled_exp_1_fu_88);

assign qk_scaled_exp_6_fu_490_p3 = ((cond60_reg_600_pp0_iter25_reg[0:0] == 1'b1) ? qk_scaled_exp_2_fu_92 : select_ln33_3_fu_476_p3);

assign qk_scaled_exp_7_fu_483_p3 = ((cond60_reg_600_pp0_iter25_reg[0:0] == 1'b1) ? qk_scaled_exp_3_fu_96 : select_ln33_2_fu_469_p3);

assign qk_scaled_exp_out = qk_scaled_exp_fu_84;

assign result_1_fu_444_p2 = (32'd0 - val_reg_636);

assign result_2_fu_449_p3 = ((xs_sign_reg_631[0:0] == 1'b1) ? result_1_fu_444_p2 : val_reg_636);

assign select_ln18_fu_376_p3 = ((tmp_fu_358_p3[0:0] == 1'b1) ? sext_ln18_fu_372_p1 : add_ln486_fu_352_p2);

assign select_ln31_fu_232_p3 = ((icmp_ln32_fu_214_p2[0:0] == 1'b1) ? add_ln31_fu_208_p2 : ap_sig_allocacmp_i_load);

assign select_ln32_fu_288_p3 = ((and_ln30_fu_226_p2[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign select_ln33_1_fu_462_p3 = ((or_ln33_reg_613_pp0_iter25_reg[0:0] == 1'b1) ? result_2_fu_449_p3 : qk_scaled_exp_fu_84);

assign select_ln33_2_fu_469_p3 = ((or_ln33_reg_613_pp0_iter25_reg[0:0] == 1'b1) ? qk_scaled_exp_3_fu_96 : result_2_fu_449_p3);

assign select_ln33_3_fu_476_p3 = ((or_ln33_reg_613_pp0_iter25_reg[0:0] == 1'b1) ? result_2_fu_449_p3 : qk_scaled_exp_2_fu_92);

assign select_ln33_4_fu_252_p3 = ((and_ln30_fu_226_p2[0:0] == 1'b1) ? qk_scaled_1_reload : qk_scaled_reload);

assign select_ln33_5_fu_260_p3 = ((and_ln30_fu_226_p2[0:0] == 1'b1) ? qk_scaled_3_reload : qk_scaled_2_reload);

assign select_ln33_6_fu_268_p3 = ((empty_fu_246_p2[0:0] == 1'b1) ? select_ln33_5_fu_260_p3 : select_ln33_4_fu_252_p3);

assign select_ln33_fu_455_p3 = ((or_ln33_reg_613_pp0_iter25_reg[0:0] == 1'b1) ? qk_scaled_exp_1_fu_88 : result_2_fu_449_p3);

assign sext_ln18_1_fu_384_p1 = $signed(select_ln18_fu_376_p3);

assign sext_ln18_fu_372_p1 = $signed(sub_ln18_fu_366_p2);

assign shl_ln18_fu_398_p2 = zext_ln15_fu_344_p1 << zext_ln18_fu_388_p1;

assign sub_ln18_fu_366_p2 = (11'd1023 - xs_exp_fu_322_p3);

assign tmp_6_fu_404_p4 = {{lshr_ln18_fu_392_p2[84:53]}};

assign tmp_7_fu_414_p4 = {{shl_ln18_fu_398_p2[84:53]}};

assign tmp_fu_358_p3 = add_ln486_fu_352_p2[32'd11];

assign trunc_ln31_fu_204_p1 = ap_sig_allocacmp_j_load[0:0];

assign trunc_ln505_fu_330_p1 = data_fu_311_p1[51:0];

assign val_fu_424_p3 = ((tmp_fu_358_p3[0:0] == 1'b1) ? tmp_6_fu_404_p4 : tmp_7_fu_414_p4);

assign xor_ln30_fu_220_p2 = (icmp_ln32_fu_214_p2 ^ 1'd1);

assign xor_ln33_fu_276_p2 = (trunc_ln31_fu_204_p1 ^ 1'd1);

assign xs_exp_fu_322_p3 = {{data_fu_311_p1[62:52]}};

assign zext_ln15_fu_344_p1 = mantissa_fu_334_p4;

assign zext_ln18_fu_388_p1 = $unsigned(sext_ln18_1_fu_384_p1);

assign zext_ln486_fu_348_p1 = xs_exp_fu_322_p3;

endmodule //attention_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4
