// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module attention_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        k_Addr_A,
        k_EN_A,
        k_WEN_A,
        k_Din_A,
        k_Dout_A,
        k_t_address0,
        k_t_ce0,
        k_t_we0,
        k_t_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] k_Addr_A;
output   k_EN_A;
output  [3:0] k_WEN_A;
output  [31:0] k_Din_A;
input  [31:0] k_Dout_A;
output  [2:0] k_t_address0;
output   k_t_ce0;
output   k_t_we0;
output  [31:0] k_t_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln7_fu_103_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [2:0] add_ln9_fu_198_p2;
reg   [2:0] add_ln9_reg_258;
wire   [63:0] zext_ln9_3_fu_185_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln9_4_fu_225_p1;
reg   [1:0] j_fu_46;
wire   [1:0] add_ln8_fu_204_p2;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_j_load;
reg   [1:0] i_fu_50;
wire   [1:0] select_ln7_1_fu_141_p3;
reg   [1:0] ap_sig_allocacmp_i_load;
reg   [2:0] indvar_flatten_fu_54;
wire   [2:0] add_ln7_1_fu_109_p2;
reg   [2:0] ap_sig_allocacmp_indvar_flatten_load;
reg    k_EN_A_local;
wire   [31:0] k_Addr_A_local;
wire   [31:0] k_Addr_A_orig;
reg    k_t_we0_local;
reg    k_t_ce0_local;
wire   [0:0] icmp_ln8_fu_127_p2;
wire   [1:0] add_ln7_fu_121_p2;
wire   [0:0] trunc_ln9_fu_153_p1;
wire   [2:0] tmp_2_fu_157_p3;
wire   [2:0] zext_ln9_1_fu_165_p1;
wire   [1:0] select_ln7_fu_133_p3;
wire   [2:0] sub_ln8_fu_169_p2;
wire   [2:0] zext_ln9_2_fu_175_p1;
wire   [2:0] add_ln9_1_fu_179_p2;
wire   [2:0] tmp_fu_190_p3;
wire   [2:0] zext_ln9_fu_149_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 j_fu_46 = 2'd0;
#0 i_fu_50 = 2'd0;
#0 indvar_flatten_fu_54 = 3'd0;
#0 ap_done_reg = 1'b0;
end

attention_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln7_fu_103_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_50 <= select_ln7_1_fu_141_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_50 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln7_fu_103_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_54 <= add_ln7_1_fu_109_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_54 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln7_fu_103_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_46 <= add_ln8_fu_204_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_46 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln9_reg_258 <= add_ln9_fu_198_p2;
    end
end

always @ (*) begin
    if (((icmp_ln7_fu_103_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_load = 2'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_50;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 3'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_54;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_load = 2'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_46;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_EN_A_local = 1'b1;
    end else begin
        k_EN_A_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_t_ce0_local = 1'b1;
    end else begin
        k_t_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_t_we0_local = 1'b1;
    end else begin
        k_t_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln7_1_fu_109_p2 = (ap_sig_allocacmp_indvar_flatten_load + 3'd1);

assign add_ln7_fu_121_p2 = (ap_sig_allocacmp_i_load + 2'd1);

assign add_ln8_fu_204_p2 = (select_ln7_fu_133_p3 + 2'd1);

assign add_ln9_1_fu_179_p2 = (sub_ln8_fu_169_p2 + zext_ln9_2_fu_175_p1);

assign add_ln9_fu_198_p2 = (tmp_fu_190_p3 + zext_ln9_fu_149_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln7_fu_103_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 3'd6) ? 1'b1 : 1'b0);

assign icmp_ln8_fu_127_p2 = ((ap_sig_allocacmp_j_load == 2'd3) ? 1'b1 : 1'b0);

assign k_Addr_A = k_Addr_A_local;

assign k_Addr_A_local = k_Addr_A_orig << 32'd2;

assign k_Addr_A_orig = zext_ln9_3_fu_185_p1;

assign k_Din_A = 32'd0;

assign k_EN_A = k_EN_A_local;

assign k_WEN_A = 4'd0;

assign k_t_address0 = zext_ln9_4_fu_225_p1;

assign k_t_ce0 = k_t_ce0_local;

assign k_t_d0 = k_Dout_A;

assign k_t_we0 = k_t_we0_local;

assign select_ln7_1_fu_141_p3 = ((icmp_ln8_fu_127_p2[0:0] == 1'b1) ? add_ln7_fu_121_p2 : ap_sig_allocacmp_i_load);

assign select_ln7_fu_133_p3 = ((icmp_ln8_fu_127_p2[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_j_load);

assign sub_ln8_fu_169_p2 = (tmp_2_fu_157_p3 - zext_ln9_1_fu_165_p1);

assign tmp_2_fu_157_p3 = {{trunc_ln9_fu_153_p1}, {2'd0}};

assign tmp_fu_190_p3 = {{select_ln7_fu_133_p3}, {1'd0}};

assign trunc_ln9_fu_153_p1 = select_ln7_1_fu_141_p3[0:0];

assign zext_ln9_1_fu_165_p1 = select_ln7_1_fu_141_p3;

assign zext_ln9_2_fu_175_p1 = select_ln7_fu_133_p3;

assign zext_ln9_3_fu_185_p1 = add_ln9_1_fu_179_p2;

assign zext_ln9_4_fu_225_p1 = add_ln9_reg_258;

assign zext_ln9_fu_149_p1 = select_ln7_1_fu_141_p3;

endmodule //attention_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2
