// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module attention_attention_Pipeline_VITIS_LOOP_8_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_r_Addr_A,
        out_r_EN_A,
        out_r_WEN_A,
        out_r_Din_A,
        out_r_Dout_A,
        out_r_Addr_B,
        out_r_EN_B,
        out_r_WEN_B,
        out_r_Din_B,
        out_r_Dout_B,
        qk_scaled_exp_2_reload,
        qk_scaled_exp_reload,
        qk_scaled_exp_3_reload,
        qk_scaled_exp_1_reload,
        v_load,
        v_load_1,
        v_load_2,
        v_load_3,
        v_load_4,
        v_load_5,
        grp_fu_465_p_din0,
        grp_fu_465_p_din1,
        grp_fu_465_p_dout0,
        grp_fu_465_p_ce,
        grp_fu_469_p_din0,
        grp_fu_469_p_din1,
        grp_fu_469_p_dout0,
        grp_fu_469_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] out_r_Addr_A;
output   out_r_EN_A;
output  [3:0] out_r_WEN_A;
output  [31:0] out_r_Din_A;
input  [31:0] out_r_Dout_A;
output  [31:0] out_r_Addr_B;
output   out_r_EN_B;
output  [3:0] out_r_WEN_B;
output  [31:0] out_r_Din_B;
input  [31:0] out_r_Dout_B;
input  [31:0] qk_scaled_exp_2_reload;
input  [31:0] qk_scaled_exp_reload;
input  [31:0] qk_scaled_exp_3_reload;
input  [31:0] qk_scaled_exp_1_reload;
input  [31:0] v_load;
input  [31:0] v_load_1;
input  [31:0] v_load_2;
input  [31:0] v_load_3;
input  [31:0] v_load_4;
input  [31:0] v_load_5;
output  [31:0] grp_fu_465_p_din0;
output  [31:0] grp_fu_465_p_din1;
input  [31:0] grp_fu_465_p_dout0;
output   grp_fu_465_p_ce;
output  [31:0] grp_fu_469_p_din0;
output  [31:0] grp_fu_469_p_din1;
input  [31:0] grp_fu_469_p_dout0;
output   grp_fu_469_p_ce;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln8_reg_348;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [31:0] reg_169;
wire    ap_block_pp0_stage0_11001;
wire    ap_block_pp0_stage1_11001;
reg   [31:0] reg_173;
reg   [1:0] i_1_reg_342;
reg   [1:0] i_1_reg_342_pp0_iter1_reg;
wire   [0:0] icmp_ln8_fu_185_p2;
wire   [0:0] empty_fu_197_p2;
reg   [0:0] empty_reg_352;
wire  signed [31:0] tmp_3_fu_208_p3;
reg  signed [31:0] tmp_3_reg_358;
wire  signed [31:0] tmp_4_fu_215_p3;
reg  signed [31:0] tmp_4_reg_365;
wire   [31:0] grp_fu_165_p2;
reg   [31:0] mul_ln13_2_reg_372;
wire   [2:0] sub_ln15_fu_235_p2;
reg   [2:0] sub_ln15_reg_377;
reg   [31:0] mul_ln13_5_reg_383;
wire    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln15_1_fu_241_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln15_2_fu_258_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln15_3_fu_268_p1;
reg   [1:0] i_fu_60;
wire   [1:0] add_ln8_fu_191_p2;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_i_1;
reg   [3:0] out_r_WEN_A_local;
reg   [31:0] out_r_Din_A_local;
wire   [31:0] sum_fu_246_p2;
reg    out_r_EN_A_local;
wire   [31:0] out_r_Addr_A_local;
reg   [31:0] out_r_Addr_A_orig;
reg   [3:0] out_r_WEN_B_local;
wire   [31:0] sum_7_fu_273_p2;
reg    out_r_EN_B_local;
wire   [31:0] out_r_Addr_B_local;
wire   [31:0] out_r_Addr_B_orig;
wire   [31:0] sum_8_fu_279_p2;
reg  signed [31:0] grp_fu_157_p0;
reg  signed [31:0] grp_fu_157_p1;
reg  signed [31:0] grp_fu_161_p0;
reg  signed [31:0] grp_fu_161_p1;
reg  signed [31:0] grp_fu_165_p0;
reg  signed [31:0] grp_fu_165_p1;
wire   [0:0] trunc_ln15_fu_224_p1;
wire   [2:0] p_shl_fu_227_p3;
wire   [2:0] zext_ln15_fu_221_p1;
wire   [2:0] add_ln15_fu_253_p2;
wire   [2:0] add_ln15_1_fu_263_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter1_stage0;
reg    ap_idle_pp0_0to0;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to2;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 i_fu_60 = 2'd0;
#0 ap_done_reg = 1'b0;
end

attention_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U34(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_165_p0),
    .din1(grp_fu_165_p1),
    .ce(1'b1),
    .dout(grp_fu_165_p2)
);

attention_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln8_fu_185_p2 == 1'd0))) begin
            i_fu_60 <= add_ln8_fu_191_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_60 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_reg_352 <= empty_fu_197_p2;
        i_1_reg_342 <= ap_sig_allocacmp_i_1;
        i_1_reg_342_pp0_iter1_reg <= i_1_reg_342;
        icmp_ln8_reg_348 <= icmp_ln8_fu_185_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mul_ln13_2_reg_372 <= grp_fu_165_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        mul_ln13_5_reg_383 <= grp_fu_165_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        reg_169 <= grp_fu_465_p_dout0;
        reg_173 <= grp_fu_469_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        sub_ln15_reg_377 <= sub_ln15_fu_235_p2;
        tmp_3_reg_358 <= tmp_3_fu_208_p3;
        tmp_4_reg_365 <= tmp_4_fu_215_p3;
    end
end

always @ (*) begin
    if (((icmp_ln8_reg_348 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln8_reg_348 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 2'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_60;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_157_p0 = v_load_3;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_157_p0 = v_load;
    end else begin
        grp_fu_157_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_157_p1 = tmp_4_reg_365;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_157_p1 = tmp_3_fu_208_p3;
    end else begin
        grp_fu_157_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_161_p0 = v_load_4;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_161_p0 = v_load_1;
    end else begin
        grp_fu_161_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_161_p1 = tmp_3_reg_358;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_161_p1 = tmp_4_fu_215_p3;
    end else begin
        grp_fu_161_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_165_p0 = v_load_5;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_165_p0 = v_load_2;
    end else begin
        grp_fu_165_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_165_p1 = tmp_4_reg_365;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_165_p1 = tmp_3_fu_208_p3;
    end else begin
        grp_fu_165_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_r_Addr_A_orig = zext_ln15_3_fu_268_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        out_r_Addr_A_orig = zext_ln15_1_fu_241_p1;
    end else begin
        out_r_Addr_A_orig = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_r_Din_A_local = sum_8_fu_279_p2;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        out_r_Din_A_local = sum_fu_246_p2;
    end else begin
        out_r_Din_A_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_r_EN_A_local = 1'b1;
    end else begin
        out_r_EN_A_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_r_EN_B_local = 1'b1;
    end else begin
        out_r_EN_B_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_r_WEN_A_local = 4'd15;
    end else begin
        out_r_WEN_A_local = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_r_WEN_B_local = 4'd15;
    end else begin
        out_r_WEN_B_local = 4'd0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln15_1_fu_263_p2 = (sub_ln15_reg_377 + 3'd2);

assign add_ln15_fu_253_p2 = (sub_ln15_reg_377 + 3'd1);

assign add_ln8_fu_191_p2 = (ap_sig_allocacmp_i_1 + 2'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign empty_fu_197_p2 = ((ap_sig_allocacmp_i_1 == 2'd1) ? 1'b1 : 1'b0);

assign grp_fu_465_p_ce = 1'b1;

assign grp_fu_465_p_din0 = grp_fu_157_p0;

assign grp_fu_465_p_din1 = grp_fu_157_p1;

assign grp_fu_469_p_ce = 1'b1;

assign grp_fu_469_p_din0 = grp_fu_161_p0;

assign grp_fu_469_p_din1 = grp_fu_161_p1;

assign icmp_ln8_fu_185_p2 = ((ap_sig_allocacmp_i_1 == 2'd2) ? 1'b1 : 1'b0);

assign out_r_Addr_A = out_r_Addr_A_local;

assign out_r_Addr_A_local = out_r_Addr_A_orig << 32'd2;

assign out_r_Addr_B = out_r_Addr_B_local;

assign out_r_Addr_B_local = out_r_Addr_B_orig << 32'd2;

assign out_r_Addr_B_orig = zext_ln15_2_fu_258_p1;

assign out_r_Din_A = out_r_Din_A_local;

assign out_r_Din_B = sum_7_fu_273_p2;

assign out_r_EN_A = out_r_EN_A_local;

assign out_r_EN_B = out_r_EN_B_local;

assign out_r_WEN_A = out_r_WEN_A_local;

assign out_r_WEN_B = out_r_WEN_B_local;

assign p_shl_fu_227_p3 = {{trunc_ln15_fu_224_p1}, {2'd0}};

assign sub_ln15_fu_235_p2 = (p_shl_fu_227_p3 - zext_ln15_fu_221_p1);

assign sum_7_fu_273_p2 = (reg_169 + mul_ln13_2_reg_372);

assign sum_8_fu_279_p2 = (mul_ln13_5_reg_383 + reg_173);

assign sum_fu_246_p2 = (reg_173 + reg_169);

assign tmp_3_fu_208_p3 = ((empty_reg_352[0:0] == 1'b1) ? qk_scaled_exp_2_reload : qk_scaled_exp_reload);

assign tmp_4_fu_215_p3 = ((empty_reg_352[0:0] == 1'b1) ? qk_scaled_exp_3_reload : qk_scaled_exp_1_reload);

assign trunc_ln15_fu_224_p1 = i_1_reg_342_pp0_iter1_reg[0:0];

assign zext_ln15_1_fu_241_p1 = sub_ln15_fu_235_p2;

assign zext_ln15_2_fu_258_p1 = add_ln15_fu_253_p2;

assign zext_ln15_3_fu_268_p1 = add_ln15_1_fu_263_p2;

assign zext_ln15_fu_221_p1 = i_1_reg_342_pp0_iter1_reg;

endmodule //attention_attention_Pipeline_VITIS_LOOP_8_1
