-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity attention_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    q_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    q_EN_A : OUT STD_LOGIC;
    q_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    q_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    q_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    q_Addr_B : OUT STD_LOGIC_VECTOR (31 downto 0);
    q_EN_B : OUT STD_LOGIC;
    q_WEN_B : OUT STD_LOGIC_VECTOR (3 downto 0);
    q_Din_B : OUT STD_LOGIC_VECTOR (31 downto 0);
    q_Dout_B : IN STD_LOGIC_VECTOR (31 downto 0);
    k_t_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    k_t_ce0 : OUT STD_LOGIC;
    k_t_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    k_t_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    k_t_ce1 : OUT STD_LOGIC;
    k_t_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    qk_124_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    qk_124_out_ap_vld : OUT STD_LOGIC;
    qk_113_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    qk_113_out_ap_vld : OUT STD_LOGIC;
    qk_102_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    qk_102_out_ap_vld : OUT STD_LOGIC;
    qk_91_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    qk_91_out_ap_vld : OUT STD_LOGIC;
    grp_fu_465_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_465_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_465_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_465_p_ce : OUT STD_LOGIC;
    grp_fu_469_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_469_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_469_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_469_p_ce : OUT STD_LOGIC );
end;


architecture behav of attention_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln8_fu_260_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal cmp6_new_phi_0_i_reg_208 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln8_reg_900 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln8_reg_900_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln8_reg_900_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln8_reg_900_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln8_reg_900_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln9_fu_275_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln9_reg_904 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln9_reg_904_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln9_reg_904_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln9_reg_904_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln9_reg_904_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln22_1_fu_345_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln22_1_reg_918 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln22_1_reg_918_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln22_1_reg_918_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln22_1_reg_918_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp6_new_phi_0_i_mid2_fu_377_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp6_new_phi_0_i_mid2_reg_927 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp6_new_phi_0_i_mid2_reg_927_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp6_new_phi_0_i_mid2_reg_927_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp6_new_phi_0_i_mid2_reg_927_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond_fu_413_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cond_reg_933 : STD_LOGIC_VECTOR (0 downto 0);
    signal cond_reg_933_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond_reg_933_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond_reg_933_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln11_fu_501_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln11_reg_961 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln11_reg_961_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln11_reg_961_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln11_reg_961_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln11_1_fu_513_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln15_fu_519_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln15_reg_972 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln15_reg_972_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln15_reg_972_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln15_reg_972_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal q_load_reg_980 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_t_load_reg_985 : STD_LOGIC_VECTOR (31 downto 0);
    signal q_load_1_reg_990 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_t_load_1_reg_995 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln13_reg_1000 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln13_1_reg_1005 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_init : STD_LOGIC;
    signal zext_ln13_1_fu_429_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln13_2_fu_446_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln13_4_fu_477_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln13_5_fu_496_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sum_fu_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal sum_5_fu_664_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_new_phi_0_i_fu_74 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal qk_9_fu_671_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_fu_78 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal k_1_fu_507_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal qk_fu_82 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal select_ln9_3_fu_633_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal qk_91_fu_86 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal qk_8_fu_727_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal qk_1_fu_90 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal select_ln9_2_fu_626_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal qk_102_fu_94 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal qk_7_fu_720_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal qk_2_fu_98 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal select_ln9_1_fu_619_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal qk_113_fu_102 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal qk_6_fu_713_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal qk_3_fu_106 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal select_ln9_fu_612_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal qk_124_fu_110 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal qk_5_fu_706_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal j_fu_114 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal select_ln9_4_fu_383_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_flatten10_fu_118 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal select_ln9_5_fu_287_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_indvar_flatten10_load : STD_LOGIC_VECTOR (3 downto 0);
    signal i_fu_122 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal select_ln8_fu_350_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_flatten34_fu_126 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln8_fu_266_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_indvar_flatten34_load : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal q_EN_B_local : STD_LOGIC;
    signal q_Addr_B_local : STD_LOGIC_VECTOR (31 downto 0);
    signal q_Addr_B_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal q_EN_A_local : STD_LOGIC;
    signal q_Addr_A_local : STD_LOGIC_VECTOR (31 downto 0);
    signal q_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal k_t_ce1_local : STD_LOGIC;
    signal k_t_ce0_local : STD_LOGIC;
    signal add_ln9_1_fu_281_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal exit_cond_1_i1314_fu_339_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln8_1_fu_314_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln22_4_fu_320_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln22_5_fu_327_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_ln22_fu_334_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_exit_cond_1_i13_mid233_fu_371_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln9_fu_357_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln13_fu_391_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_395_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln13_fu_403_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal sub_ln13_fu_407_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal k_1_mid2_fu_363_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln13_fu_423_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal shl_ln13_fu_434_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln9_4_cast_fu_419_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln13_1_fu_440_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_451_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln_fu_459_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln13_3_fu_467_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln13_2_fu_471_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_5_fu_482_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln13_3_fu_490_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln22_6_fu_598_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln22_fu_570_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln22_1_fu_577_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln22_2_fu_584_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln22_3_fu_591_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_mid2_fu_605_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_1_fu_640_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_2_fu_645_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_4_fu_659_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_3_fu_652_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln15_2_fu_692_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln15_3_fu_699_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln15_fu_678_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln15_1_fu_685_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_703 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component attention_mul_32s_32s_32_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component attention_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component attention_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    cmp6_new_phi_0_i_reg_208_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_init = ap_const_logic_1))) then 
                    cmp6_new_phi_0_i_reg_208 <= ap_const_lv1_1;
                elsif ((ap_const_boolean_1 = ap_condition_703)) then 
                    cmp6_new_phi_0_i_reg_208 <= icmp_ln11_1_fu_513_p2;
                end if;
            end if; 
        end if;
    end process;

    i_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_122 <= ap_const_lv2_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln8_reg_900 = ap_const_lv1_0))) then 
                    i_fu_122 <= select_ln8_fu_350_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten10_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln8_fu_260_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten10_fu_118 <= select_ln9_5_fu_287_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten10_fu_118 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten34_fu_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln8_fu_260_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten34_fu_126 <= add_ln8_fu_266_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten34_fu_126 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_114 <= ap_const_lv2_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln8_reg_900 = ap_const_lv1_0))) then 
                    j_fu_114 <= select_ln9_4_fu_383_p3;
                end if;
            end if; 
        end if;
    end process;

    k_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    k_fu_78 <= ap_const_lv3_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln8_reg_900 = ap_const_lv1_0))) then 
                    k_fu_78 <= k_1_fu_507_p2;
                end if;
            end if; 
        end if;
    end process;

    sum_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    sum_fu_70 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln8_reg_900_pp0_iter4_reg = ap_const_lv1_0))) then 
                    sum_fu_70 <= sum_5_fu_664_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln8_reg_900_pp0_iter4_reg = ap_const_lv1_0))) then
                add_new_phi_0_i_fu_74 <= qk_9_fu_671_p3;
                qk_102_fu_94 <= qk_7_fu_720_p3;
                qk_113_fu_102 <= qk_6_fu_713_p3;
                qk_124_fu_110 <= qk_5_fu_706_p3;
                qk_1_fu_90 <= select_ln9_2_fu_626_p3;
                qk_2_fu_98 <= select_ln9_1_fu_619_p3;
                qk_3_fu_106 <= select_ln9_fu_612_p3;
                qk_91_fu_86 <= qk_8_fu_727_p3;
                qk_fu_82 <= select_ln9_3_fu_633_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                cmp6_new_phi_0_i_mid2_reg_927 <= cmp6_new_phi_0_i_mid2_fu_377_p2;
                cond_reg_933 <= cond_fu_413_p2;
                icmp_ln11_reg_961 <= icmp_ln11_fu_501_p2;
                icmp_ln15_reg_972 <= icmp_ln15_fu_519_p2;
                icmp_ln8_reg_900 <= icmp_ln8_fu_260_p2;
                icmp_ln8_reg_900_pp0_iter1_reg <= icmp_ln8_reg_900;
                icmp_ln9_reg_904 <= icmp_ln9_fu_275_p2;
                icmp_ln9_reg_904_pp0_iter1_reg <= icmp_ln9_reg_904;
                or_ln22_1_reg_918 <= or_ln22_1_fu_345_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                cmp6_new_phi_0_i_mid2_reg_927_pp0_iter2_reg <= cmp6_new_phi_0_i_mid2_reg_927;
                cmp6_new_phi_0_i_mid2_reg_927_pp0_iter3_reg <= cmp6_new_phi_0_i_mid2_reg_927_pp0_iter2_reg;
                cmp6_new_phi_0_i_mid2_reg_927_pp0_iter4_reg <= cmp6_new_phi_0_i_mid2_reg_927_pp0_iter3_reg;
                cond_reg_933_pp0_iter2_reg <= cond_reg_933;
                cond_reg_933_pp0_iter3_reg <= cond_reg_933_pp0_iter2_reg;
                cond_reg_933_pp0_iter4_reg <= cond_reg_933_pp0_iter3_reg;
                icmp_ln11_reg_961_pp0_iter2_reg <= icmp_ln11_reg_961;
                icmp_ln11_reg_961_pp0_iter3_reg <= icmp_ln11_reg_961_pp0_iter2_reg;
                icmp_ln11_reg_961_pp0_iter4_reg <= icmp_ln11_reg_961_pp0_iter3_reg;
                icmp_ln15_reg_972_pp0_iter2_reg <= icmp_ln15_reg_972;
                icmp_ln15_reg_972_pp0_iter3_reg <= icmp_ln15_reg_972_pp0_iter2_reg;
                icmp_ln15_reg_972_pp0_iter4_reg <= icmp_ln15_reg_972_pp0_iter3_reg;
                icmp_ln8_reg_900_pp0_iter2_reg <= icmp_ln8_reg_900_pp0_iter1_reg;
                icmp_ln8_reg_900_pp0_iter3_reg <= icmp_ln8_reg_900_pp0_iter2_reg;
                icmp_ln8_reg_900_pp0_iter4_reg <= icmp_ln8_reg_900_pp0_iter3_reg;
                icmp_ln9_reg_904_pp0_iter2_reg <= icmp_ln9_reg_904_pp0_iter1_reg;
                icmp_ln9_reg_904_pp0_iter3_reg <= icmp_ln9_reg_904_pp0_iter2_reg;
                icmp_ln9_reg_904_pp0_iter4_reg <= icmp_ln9_reg_904_pp0_iter3_reg;
                mul_ln13_1_reg_1005 <= grp_fu_469_p_dout0;
                mul_ln13_reg_1000 <= grp_fu_465_p_dout0;
                or_ln22_1_reg_918_pp0_iter2_reg <= or_ln22_1_reg_918;
                or_ln22_1_reg_918_pp0_iter3_reg <= or_ln22_1_reg_918_pp0_iter2_reg;
                or_ln22_1_reg_918_pp0_iter4_reg <= or_ln22_1_reg_918_pp0_iter3_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                k_t_load_1_reg_995 <= k_t_q0;
                k_t_load_reg_985 <= k_t_q1;
                q_load_1_reg_990 <= q_Dout_A;
                q_load_reg_980 <= q_Dout_B;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln13_1_fu_440_p2 <= std_logic_vector(unsigned(shl_ln13_fu_434_p2) + unsigned(select_ln9_4_cast_fu_419_p1));
    add_ln13_2_fu_471_p2 <= std_logic_vector(unsigned(sub_ln13_fu_407_p2) + unsigned(zext_ln13_3_fu_467_p1));
    add_ln13_3_fu_490_p2 <= std_logic_vector(unsigned(tmp_5_fu_482_p3) + unsigned(select_ln9_4_cast_fu_419_p1));
    add_ln13_fu_423_p2 <= std_logic_vector(unsigned(sub_ln13_fu_407_p2) + unsigned(k_1_mid2_fu_363_p3));
    add_ln8_1_fu_314_p2 <= std_logic_vector(unsigned(i_fu_122) + unsigned(ap_const_lv2_1));
    add_ln8_fu_266_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten34_load) + unsigned(ap_const_lv4_1));
    add_ln9_1_fu_281_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten10_load) + unsigned(ap_const_lv4_1));
    add_ln9_fu_357_p2 <= std_logic_vector(unsigned(select_ln22_4_fu_320_p3) + unsigned(ap_const_lv2_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_703_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln8_reg_900)
    begin
                ap_condition_703 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln8_reg_900 = ap_const_lv1_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln8_fu_260_p2)
    begin
        if (((icmp_ln8_fu_260_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln8_reg_900)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln8_reg_900 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter4_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten10_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, indvar_flatten10_fu_118)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten10_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_indvar_flatten10_load <= indvar_flatten10_fu_118;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten34_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, indvar_flatten34_fu_126)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten34_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_indvar_flatten34_load <= indvar_flatten34_fu_126;
        end if; 
    end process;

    cmp6_new_phi_0_i_mid2_fu_377_p2 <= (or_ln22_fu_334_p2 or not_exit_cond_1_i13_mid233_fu_371_p2);
    cond_fu_413_p2 <= "1" when (select_ln8_fu_350_p3 = ap_const_lv2_0) else "0";
    exit_cond_1_i1314_fu_339_p2 <= "1" when (unsigned(k_fu_78) < unsigned(ap_const_lv3_3)) else "0";
    grp_fu_465_p_ce <= ap_const_logic_1;
    grp_fu_465_p_din0 <= k_t_load_reg_985;
    grp_fu_465_p_din1 <= q_load_reg_980;
    grp_fu_469_p_ce <= ap_const_logic_1;
    grp_fu_469_p_din0 <= k_t_load_1_reg_995;
    grp_fu_469_p_din1 <= q_load_1_reg_990;
    icmp_ln11_1_fu_513_p2 <= "1" when (unsigned(k_1_fu_507_p2) < unsigned(ap_const_lv3_3)) else "0";
    icmp_ln11_fu_501_p2 <= "0" when (or_ln_fu_459_p3 = ap_const_lv2_3) else "1";
    icmp_ln15_fu_519_p2 <= "1" when (select_ln9_4_fu_383_p3 = ap_const_lv2_0) else "0";
    icmp_ln8_fu_260_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten34_load = ap_const_lv4_8) else "0";
    icmp_ln9_fu_275_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten10_load = ap_const_lv4_4) else "0";
    k_1_fu_507_p2 <= std_logic_vector(unsigned(k_1_mid2_fu_363_p3) + unsigned(ap_const_lv3_2));
    k_1_mid2_fu_363_p3 <= 
        select_ln22_5_fu_327_p3 when (or_ln22_1_fu_345_p2(0) = '1') else 
        ap_const_lv3_0;
    k_t_address0 <= zext_ln13_5_fu_496_p1(3 - 1 downto 0);
    k_t_address1 <= zext_ln13_2_fu_446_p1(3 - 1 downto 0);
    k_t_ce0 <= k_t_ce0_local;

    k_t_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            k_t_ce0_local <= ap_const_logic_1;
        else 
            k_t_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    k_t_ce1 <= k_t_ce1_local;

    k_t_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            k_t_ce1_local <= ap_const_logic_1;
        else 
            k_t_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    not_exit_cond_1_i13_mid233_fu_371_p2 <= (or_ln22_1_fu_345_p2 xor ap_const_lv1_1);
    or_ln22_1_fu_345_p2 <= (icmp_ln9_reg_904 or exit_cond_1_i1314_fu_339_p2);
    or_ln22_fu_334_p2 <= (icmp_ln9_reg_904 or cmp6_new_phi_0_i_reg_208);
    or_ln_fu_459_p3 <= (tmp_1_fu_451_p3 & ap_const_lv1_1);
    q_Addr_A <= q_Addr_A_local;
    q_Addr_A_local <= std_logic_vector(shift_left(unsigned(q_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    q_Addr_A_orig <= zext_ln13_4_fu_477_p1(32 - 1 downto 0);
    q_Addr_B <= q_Addr_B_local;
    q_Addr_B_local <= std_logic_vector(shift_left(unsigned(q_Addr_B_orig),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    q_Addr_B_orig <= zext_ln13_1_fu_429_p1(32 - 1 downto 0);
    q_Din_A <= ap_const_lv32_0;
    q_Din_B <= ap_const_lv32_0;
    q_EN_A <= q_EN_A_local;

    q_EN_A_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            q_EN_A_local <= ap_const_logic_1;
        else 
            q_EN_A_local <= ap_const_logic_0;
        end if; 
    end process;

    q_EN_B <= q_EN_B_local;

    q_EN_B_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            q_EN_B_local <= ap_const_logic_1;
        else 
            q_EN_B_local <= ap_const_logic_0;
        end if; 
    end process;

    q_WEN_A <= ap_const_lv4_0;
    q_WEN_B <= ap_const_lv4_0;
    qk_102_out <= qk_102_fu_94;

    qk_102_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln8_reg_900_pp0_iter3_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (icmp_ln8_reg_900_pp0_iter3_reg = ap_const_lv1_1))) then 
            qk_102_out_ap_vld <= ap_const_logic_1;
        else 
            qk_102_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    qk_113_out <= qk_113_fu_102;

    qk_113_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln8_reg_900_pp0_iter3_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (icmp_ln8_reg_900_pp0_iter3_reg = ap_const_lv1_1))) then 
            qk_113_out_ap_vld <= ap_const_logic_1;
        else 
            qk_113_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    qk_124_out <= qk_124_fu_110;

    qk_124_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln8_reg_900_pp0_iter3_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (icmp_ln8_reg_900_pp0_iter3_reg = ap_const_lv1_1))) then 
            qk_124_out_ap_vld <= ap_const_logic_1;
        else 
            qk_124_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    qk_5_fu_706_p3 <= 
        select_ln9_fu_612_p3 when (cond_reg_933_pp0_iter4_reg(0) = '1') else 
        select_ln15_2_fu_692_p3;
    qk_6_fu_713_p3 <= 
        select_ln9_1_fu_619_p3 when (cond_reg_933_pp0_iter4_reg(0) = '1') else 
        select_ln15_3_fu_699_p3;
    qk_7_fu_720_p3 <= 
        select_ln15_fu_678_p3 when (cond_reg_933_pp0_iter4_reg(0) = '1') else 
        select_ln9_2_fu_626_p3;
    qk_8_fu_727_p3 <= 
        select_ln15_1_fu_685_p3 when (cond_reg_933_pp0_iter4_reg(0) = '1') else 
        select_ln9_3_fu_633_p3;
    qk_91_out <= qk_91_fu_86;

    qk_91_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln8_reg_900_pp0_iter3_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (icmp_ln8_reg_900_pp0_iter3_reg = ap_const_lv1_1))) then 
            qk_91_out_ap_vld <= ap_const_logic_1;
        else 
            qk_91_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    qk_9_fu_671_p3 <= 
        sum_4_fu_659_p2 when (icmp_ln11_reg_961_pp0_iter4_reg(0) = '1') else 
        sum_3_fu_652_p3;
    select_ln15_1_fu_685_p3 <= 
        qk_9_fu_671_p3 when (icmp_ln15_reg_972_pp0_iter4_reg(0) = '1') else 
        select_ln9_3_fu_633_p3;
    select_ln15_2_fu_692_p3 <= 
        select_ln9_fu_612_p3 when (icmp_ln15_reg_972_pp0_iter4_reg(0) = '1') else 
        qk_9_fu_671_p3;
    select_ln15_3_fu_699_p3 <= 
        qk_9_fu_671_p3 when (icmp_ln15_reg_972_pp0_iter4_reg(0) = '1') else 
        select_ln9_1_fu_619_p3;
    select_ln15_fu_678_p3 <= 
        select_ln9_2_fu_626_p3 when (icmp_ln15_reg_972_pp0_iter4_reg(0) = '1') else 
        qk_9_fu_671_p3;
    select_ln22_1_fu_577_p3 <= 
        qk_113_fu_102 when (icmp_ln9_reg_904_pp0_iter4_reg(0) = '1') else 
        qk_2_fu_98;
    select_ln22_2_fu_584_p3 <= 
        qk_102_fu_94 when (icmp_ln9_reg_904_pp0_iter4_reg(0) = '1') else 
        qk_1_fu_90;
    select_ln22_3_fu_591_p3 <= 
        qk_91_fu_86 when (icmp_ln9_reg_904_pp0_iter4_reg(0) = '1') else 
        qk_fu_82;
    select_ln22_4_fu_320_p3 <= 
        ap_const_lv2_0 when (icmp_ln9_reg_904(0) = '1') else 
        j_fu_114;
    select_ln22_5_fu_327_p3 <= 
        ap_const_lv3_0 when (icmp_ln9_reg_904(0) = '1') else 
        k_fu_78;
    select_ln22_6_fu_598_p3 <= 
        ap_const_lv32_0 when (icmp_ln9_reg_904_pp0_iter4_reg(0) = '1') else 
        sum_fu_70;
    select_ln22_fu_570_p3 <= 
        qk_124_fu_110 when (icmp_ln9_reg_904_pp0_iter4_reg(0) = '1') else 
        qk_3_fu_106;
    select_ln8_fu_350_p3 <= 
        add_ln8_1_fu_314_p2 when (icmp_ln9_reg_904(0) = '1') else 
        i_fu_122;
    select_ln9_1_fu_619_p3 <= 
        select_ln22_1_fu_577_p3 when (or_ln22_1_reg_918_pp0_iter4_reg(0) = '1') else 
        qk_113_fu_102;
    select_ln9_2_fu_626_p3 <= 
        select_ln22_2_fu_584_p3 when (or_ln22_1_reg_918_pp0_iter4_reg(0) = '1') else 
        qk_102_fu_94;
    select_ln9_3_fu_633_p3 <= 
        select_ln22_3_fu_591_p3 when (or_ln22_1_reg_918_pp0_iter4_reg(0) = '1') else 
        qk_91_fu_86;
    select_ln9_4_cast_fu_419_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln9_4_fu_383_p3),3));
    select_ln9_4_fu_383_p3 <= 
        select_ln22_4_fu_320_p3 when (or_ln22_1_fu_345_p2(0) = '1') else 
        add_ln9_fu_357_p2;
    select_ln9_5_fu_287_p3 <= 
        ap_const_lv4_1 when (icmp_ln9_fu_275_p2(0) = '1') else 
        add_ln9_1_fu_281_p2;
    select_ln9_fu_612_p3 <= 
        select_ln22_fu_570_p3 when (or_ln22_1_reg_918_pp0_iter4_reg(0) = '1') else 
        qk_124_fu_110;
    shl_ln13_fu_434_p2 <= std_logic_vector(shift_left(unsigned(k_1_mid2_fu_363_p3),to_integer(unsigned('0' & ap_const_lv3_1(3-1 downto 0)))));
    sub_ln13_fu_407_p2 <= std_logic_vector(unsigned(tmp_fu_395_p3) - unsigned(zext_ln13_fu_403_p1));
    sum_1_fu_640_p2 <= std_logic_vector(unsigned(mul_ln13_reg_1000) + unsigned(sum_mid2_fu_605_p3));
    sum_2_fu_645_p3 <= 
        sum_1_fu_640_p2 when (cmp6_new_phi_0_i_mid2_reg_927_pp0_iter4_reg(0) = '1') else 
        sum_mid2_fu_605_p3;
    sum_3_fu_652_p3 <= 
        sum_1_fu_640_p2 when (cmp6_new_phi_0_i_mid2_reg_927_pp0_iter4_reg(0) = '1') else 
        add_new_phi_0_i_fu_74;
    sum_4_fu_659_p2 <= std_logic_vector(unsigned(mul_ln13_1_reg_1005) + unsigned(sum_2_fu_645_p3));
    sum_5_fu_664_p3 <= 
        sum_4_fu_659_p2 when (icmp_ln11_reg_961_pp0_iter4_reg(0) = '1') else 
        sum_2_fu_645_p3;
    sum_mid2_fu_605_p3 <= 
        select_ln22_6_fu_598_p3 when (or_ln22_1_reg_918_pp0_iter4_reg(0) = '1') else 
        ap_const_lv32_0;
    tmp_1_fu_451_p3 <= k_1_mid2_fu_363_p3(1 downto 1);
    tmp_5_fu_482_p3 <= (tmp_1_fu_451_p3 & ap_const_lv2_2);
    tmp_fu_395_p3 <= (trunc_ln13_fu_391_p1 & ap_const_lv2_0);
    trunc_ln13_fu_391_p1 <= select_ln8_fu_350_p3(1 - 1 downto 0);
    zext_ln13_1_fu_429_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln13_fu_423_p2),64));
    zext_ln13_2_fu_446_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln13_1_fu_440_p2),64));
    zext_ln13_3_fu_467_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln_fu_459_p3),3));
    zext_ln13_4_fu_477_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln13_2_fu_471_p2),64));
    zext_ln13_5_fu_496_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln13_3_fu_490_p2),64));
    zext_ln13_fu_403_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln8_fu_350_p3),3));
end behav;
