-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity attention is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    out_r_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_r_EN_A : OUT STD_LOGIC;
    out_r_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_r_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_r_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    out_r_Clk_A : OUT STD_LOGIC;
    out_r_Rst_A : OUT STD_LOGIC;
    out_r_Addr_B : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_r_EN_B : OUT STD_LOGIC;
    out_r_WEN_B : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_r_Din_B : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_r_Dout_B : IN STD_LOGIC_VECTOR (31 downto 0);
    out_r_Clk_B : OUT STD_LOGIC;
    out_r_Rst_B : OUT STD_LOGIC;
    q_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    q_EN_A : OUT STD_LOGIC;
    q_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    q_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    q_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    q_Clk_A : OUT STD_LOGIC;
    q_Rst_A : OUT STD_LOGIC;
    q_Addr_B : OUT STD_LOGIC_VECTOR (31 downto 0);
    q_EN_B : OUT STD_LOGIC;
    q_WEN_B : OUT STD_LOGIC_VECTOR (3 downto 0);
    q_Din_B : OUT STD_LOGIC_VECTOR (31 downto 0);
    q_Dout_B : IN STD_LOGIC_VECTOR (31 downto 0);
    q_Clk_B : OUT STD_LOGIC;
    q_Rst_B : OUT STD_LOGIC;
    k_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    k_EN_A : OUT STD_LOGIC;
    k_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    k_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    k_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    k_Clk_A : OUT STD_LOGIC;
    k_Rst_A : OUT STD_LOGIC;
    v_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    v_EN_A : OUT STD_LOGIC;
    v_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    v_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    v_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    v_Clk_A : OUT STD_LOGIC;
    v_Rst_A : OUT STD_LOGIC;
    v_Addr_B : OUT STD_LOGIC_VECTOR (31 downto 0);
    v_EN_B : OUT STD_LOGIC;
    v_WEN_B : OUT STD_LOGIC_VECTOR (3 downto 0);
    v_Din_B : OUT STD_LOGIC_VECTOR (31 downto 0);
    v_Dout_B : IN STD_LOGIC_VECTOR (31 downto 0);
    v_Clk_B : OUT STD_LOGIC;
    v_Rst_B : OUT STD_LOGIC;
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of attention is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "attention_attention,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu50-fsvh2104-2-e,HLS_INPUT_CLOCK=3.333000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.929000,HLS_SYN_LAT=110,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=6388,HLS_SYN_LUT=8316,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (9 downto 0) := "0000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (9 downto 0) := "0000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (9 downto 0) := "0001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (9 downto 0) := "0010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (9 downto 0) := "0100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_3 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_4 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000100";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv64_5 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000101";

attribute shreg_extract : string;
    signal ap_rst_reg_2 : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_reg_2 : signal is "no";
    signal ap_rst_reg_1 : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_reg_1 : signal is "no";
    signal ap_rst_n_inv : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_n_inv : signal is "no";
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_continue : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal d_k : STD_LOGIC_VECTOR (31 downto 0);
    signal d_k_read_reg_364 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_ap_done : STD_LOGIC;
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal v_load_reg_413 : STD_LOGIC_VECTOR (31 downto 0);
    signal v_load_1_reg_418 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_ap_done : STD_LOGIC;
    signal v_load_2_reg_433 : STD_LOGIC_VECTOR (31 downto 0);
    signal v_load_3_reg_438 : STD_LOGIC_VECTOR (31 downto 0);
    signal v_load_4_reg_455 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal v_load_5_reg_460 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_t_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal k_t_ce0 : STD_LOGIC;
    signal k_t_we0 : STD_LOGIC;
    signal k_t_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_t_ce1 : STD_LOGIC;
    signal k_t_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_ap_start : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_ap_done : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_ap_idle : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_ap_ready : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_k_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_k_EN_A : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_k_WEN_A : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_k_Din_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_k_t_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_k_t_ce0 : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_k_t_we0 : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_k_t_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_ap_start : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_ap_done : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_ap_idle : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_ap_ready : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_q_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_q_EN_A : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_q_WEN_A : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_q_Din_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_q_Addr_B : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_q_EN_B : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_q_WEN_B : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_q_Din_B : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_k_t_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_k_t_ce0 : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_k_t_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_k_t_ce1 : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_qk_124_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_qk_124_out_ap_vld : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_qk_113_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_qk_113_out_ap_vld : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_qk_102_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_qk_102_out_ap_vld : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_qk_91_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_qk_91_out_ap_vld : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_grp_fu_465_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_grp_fu_465_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_grp_fu_465_p_ce : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_grp_fu_469_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_grp_fu_469_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_grp_fu_469_p_ce : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_ap_start : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_ap_idle : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_ap_ready : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_qk_scaled_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_qk_scaled_3_out_ap_vld : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_qk_scaled_2_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_qk_scaled_2_out_ap_vld : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_qk_scaled_1_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_qk_scaled_1_out_ap_vld : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_qk_scaled_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_qk_scaled_out_ap_vld : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_ap_start : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_ap_idle : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_ap_ready : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_qk_scaled_exp_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_qk_scaled_exp_3_out_ap_vld : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_qk_scaled_exp_2_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_qk_scaled_exp_2_out_ap_vld : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_qk_scaled_exp_1_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_qk_scaled_exp_1_out_ap_vld : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_qk_scaled_exp_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_qk_scaled_exp_out_ap_vld : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_ap_start : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_ap_done : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_ap_idle : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_ap_ready : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_out_r_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_out_r_EN_A : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_out_r_WEN_A : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_out_r_Din_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_out_r_Addr_B : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_out_r_EN_B : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_out_r_WEN_B : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_out_r_Din_B : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_grp_fu_465_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_grp_fu_465_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_grp_fu_465_p_ce : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_grp_fu_469_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_grp_fu_469_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_grp_fu_469_p_ce : STD_LOGIC;
    signal grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call34 : BOOLEAN;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_ap_start_reg : STD_LOGIC := '0';
    signal grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_ap_start_reg : STD_LOGIC := '0';
    signal grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal v_EN_B_local : STD_LOGIC;
    signal v_Addr_B_local : STD_LOGIC_VECTOR (31 downto 0);
    signal v_Addr_B_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal v_EN_A_local : STD_LOGIC;
    signal v_Addr_A_local : STD_LOGIC_VECTOR (31 downto 0);
    signal v_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_465_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_465_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_465_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_465_ce : STD_LOGIC;
    signal grp_fu_469_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_469_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_469_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_469_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component attention_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        k_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        k_EN_A : OUT STD_LOGIC;
        k_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
        k_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        k_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
        k_t_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        k_t_ce0 : OUT STD_LOGIC;
        k_t_we0 : OUT STD_LOGIC;
        k_t_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component attention_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        q_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        q_EN_A : OUT STD_LOGIC;
        q_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
        q_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        q_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
        q_Addr_B : OUT STD_LOGIC_VECTOR (31 downto 0);
        q_EN_B : OUT STD_LOGIC;
        q_WEN_B : OUT STD_LOGIC_VECTOR (3 downto 0);
        q_Din_B : OUT STD_LOGIC_VECTOR (31 downto 0);
        q_Dout_B : IN STD_LOGIC_VECTOR (31 downto 0);
        k_t_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        k_t_ce0 : OUT STD_LOGIC;
        k_t_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        k_t_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
        k_t_ce1 : OUT STD_LOGIC;
        k_t_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        qk_124_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        qk_124_out_ap_vld : OUT STD_LOGIC;
        qk_113_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        qk_113_out_ap_vld : OUT STD_LOGIC;
        qk_102_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        qk_102_out_ap_vld : OUT STD_LOGIC;
        qk_91_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        qk_91_out_ap_vld : OUT STD_LOGIC;
        grp_fu_465_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_465_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_465_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_465_p_ce : OUT STD_LOGIC;
        grp_fu_469_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_469_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_469_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_469_p_ce : OUT STD_LOGIC );
    end component;


    component attention_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        qk_102_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        qk_91_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        qk_124_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        qk_113_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        d_k : IN STD_LOGIC_VECTOR (31 downto 0);
        qk_scaled_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        qk_scaled_3_out_ap_vld : OUT STD_LOGIC;
        qk_scaled_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        qk_scaled_2_out_ap_vld : OUT STD_LOGIC;
        qk_scaled_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        qk_scaled_1_out_ap_vld : OUT STD_LOGIC;
        qk_scaled_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        qk_scaled_out_ap_vld : OUT STD_LOGIC );
    end component;


    component attention_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        qk_scaled_1_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        qk_scaled_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        qk_scaled_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        qk_scaled_2_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        qk_scaled_exp_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        qk_scaled_exp_3_out_ap_vld : OUT STD_LOGIC;
        qk_scaled_exp_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        qk_scaled_exp_2_out_ap_vld : OUT STD_LOGIC;
        qk_scaled_exp_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        qk_scaled_exp_1_out_ap_vld : OUT STD_LOGIC;
        qk_scaled_exp_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        qk_scaled_exp_out_ap_vld : OUT STD_LOGIC );
    end component;


    component attention_attention_Pipeline_VITIS_LOOP_8_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        out_r_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_r_EN_A : OUT STD_LOGIC;
        out_r_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_r_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_r_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
        out_r_Addr_B : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_r_EN_B : OUT STD_LOGIC;
        out_r_WEN_B : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_r_Din_B : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_r_Dout_B : IN STD_LOGIC_VECTOR (31 downto 0);
        qk_scaled_exp_2_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        qk_scaled_exp_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        qk_scaled_exp_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        qk_scaled_exp_1_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        v_load : IN STD_LOGIC_VECTOR (31 downto 0);
        v_load_1 : IN STD_LOGIC_VECTOR (31 downto 0);
        v_load_2 : IN STD_LOGIC_VECTOR (31 downto 0);
        v_load_3 : IN STD_LOGIC_VECTOR (31 downto 0);
        v_load_4 : IN STD_LOGIC_VECTOR (31 downto 0);
        v_load_5 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_465_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_465_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_465_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_465_p_ce : OUT STD_LOGIC;
        grp_fu_469_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_469_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_469_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_469_p_ce : OUT STD_LOGIC );
    end component;


    component attention_mul_32s_32s_32_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component attention_k_t_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component attention_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        d_k : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_continue : OUT STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;



begin
    k_t_U : component attention_k_t_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 6,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => k_t_address0,
        ce0 => k_t_ce0,
        we0 => k_t_we0,
        d0 => grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_k_t_d0,
        q0 => k_t_q0,
        address1 => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_k_t_address1,
        ce1 => k_t_ce1,
        q1 => k_t_q1);

    grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181 : component attention_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_ap_start,
        ap_done => grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_ap_done,
        ap_idle => grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_ap_idle,
        ap_ready => grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_ap_ready,
        k_Addr_A => grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_k_Addr_A,
        k_EN_A => grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_k_EN_A,
        k_WEN_A => grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_k_WEN_A,
        k_Din_A => grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_k_Din_A,
        k_Dout_A => k_Dout_A,
        k_t_address0 => grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_k_t_address0,
        k_t_ce0 => grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_k_t_ce0,
        k_t_we0 => grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_k_t_we0,
        k_t_d0 => grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_k_t_d0);

    grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189 : component attention_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_ap_start,
        ap_done => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_ap_done,
        ap_idle => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_ap_idle,
        ap_ready => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_ap_ready,
        q_Addr_A => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_q_Addr_A,
        q_EN_A => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_q_EN_A,
        q_WEN_A => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_q_WEN_A,
        q_Din_A => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_q_Din_A,
        q_Dout_A => q_Dout_A,
        q_Addr_B => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_q_Addr_B,
        q_EN_B => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_q_EN_B,
        q_WEN_B => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_q_WEN_B,
        q_Din_B => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_q_Din_B,
        q_Dout_B => q_Dout_B,
        k_t_address0 => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_k_t_address0,
        k_t_ce0 => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_k_t_ce0,
        k_t_q0 => k_t_q0,
        k_t_address1 => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_k_t_address1,
        k_t_ce1 => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_k_t_ce1,
        k_t_q1 => k_t_q1,
        qk_124_out => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_qk_124_out,
        qk_124_out_ap_vld => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_qk_124_out_ap_vld,
        qk_113_out => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_qk_113_out,
        qk_113_out_ap_vld => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_qk_113_out_ap_vld,
        qk_102_out => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_qk_102_out,
        qk_102_out_ap_vld => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_qk_102_out_ap_vld,
        qk_91_out => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_qk_91_out,
        qk_91_out_ap_vld => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_qk_91_out_ap_vld,
        grp_fu_465_p_din0 => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_grp_fu_465_p_din0,
        grp_fu_465_p_din1 => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_grp_fu_465_p_din1,
        grp_fu_465_p_dout0 => grp_fu_465_p2,
        grp_fu_465_p_ce => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_grp_fu_465_p_ce,
        grp_fu_469_p_din0 => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_grp_fu_469_p_din0,
        grp_fu_469_p_din1 => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_grp_fu_469_p_din1,
        grp_fu_469_p_dout0 => grp_fu_469_p2,
        grp_fu_469_p_ce => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_grp_fu_469_p_ce);

    grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200 : component attention_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_ap_start,
        ap_done => grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_ap_done,
        ap_idle => grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_ap_idle,
        ap_ready => grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_ap_ready,
        qk_102_reload => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_qk_102_out,
        qk_91_reload => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_qk_91_out,
        qk_124_reload => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_qk_124_out,
        qk_113_reload => grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_qk_113_out,
        d_k => d_k_read_reg_364,
        qk_scaled_3_out => grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_qk_scaled_3_out,
        qk_scaled_3_out_ap_vld => grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_qk_scaled_3_out_ap_vld,
        qk_scaled_2_out => grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_qk_scaled_2_out,
        qk_scaled_2_out_ap_vld => grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_qk_scaled_2_out_ap_vld,
        qk_scaled_1_out => grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_qk_scaled_1_out,
        qk_scaled_1_out_ap_vld => grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_qk_scaled_1_out_ap_vld,
        qk_scaled_out => grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_qk_scaled_out,
        qk_scaled_out_ap_vld => grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_qk_scaled_out_ap_vld);

    grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214 : component attention_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_ap_start,
        ap_done => grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_ap_done,
        ap_idle => grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_ap_idle,
        ap_ready => grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_ap_ready,
        qk_scaled_1_reload => grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_qk_scaled_1_out,
        qk_scaled_reload => grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_qk_scaled_out,
        qk_scaled_3_reload => grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_qk_scaled_3_out,
        qk_scaled_2_reload => grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_qk_scaled_2_out,
        qk_scaled_exp_3_out => grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_qk_scaled_exp_3_out,
        qk_scaled_exp_3_out_ap_vld => grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_qk_scaled_exp_3_out_ap_vld,
        qk_scaled_exp_2_out => grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_qk_scaled_exp_2_out,
        qk_scaled_exp_2_out_ap_vld => grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_qk_scaled_exp_2_out_ap_vld,
        qk_scaled_exp_1_out => grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_qk_scaled_exp_1_out,
        qk_scaled_exp_1_out_ap_vld => grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_qk_scaled_exp_1_out_ap_vld,
        qk_scaled_exp_out => grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_qk_scaled_exp_out,
        qk_scaled_exp_out_ap_vld => grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_qk_scaled_exp_out_ap_vld);

    grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226 : component attention_attention_Pipeline_VITIS_LOOP_8_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_ap_start,
        ap_done => grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_ap_done,
        ap_idle => grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_ap_idle,
        ap_ready => grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_ap_ready,
        out_r_Addr_A => grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_out_r_Addr_A,
        out_r_EN_A => grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_out_r_EN_A,
        out_r_WEN_A => grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_out_r_WEN_A,
        out_r_Din_A => grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_out_r_Din_A,
        out_r_Dout_A => ap_const_lv32_0,
        out_r_Addr_B => grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_out_r_Addr_B,
        out_r_EN_B => grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_out_r_EN_B,
        out_r_WEN_B => grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_out_r_WEN_B,
        out_r_Din_B => grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_out_r_Din_B,
        out_r_Dout_B => ap_const_lv32_0,
        qk_scaled_exp_2_reload => grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_qk_scaled_exp_2_out,
        qk_scaled_exp_reload => grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_qk_scaled_exp_out,
        qk_scaled_exp_3_reload => grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_qk_scaled_exp_3_out,
        qk_scaled_exp_1_reload => grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_qk_scaled_exp_1_out,
        v_load => v_load_reg_413,
        v_load_1 => v_load_1_reg_418,
        v_load_2 => v_load_2_reg_433,
        v_load_3 => v_load_3_reg_438,
        v_load_4 => v_load_4_reg_455,
        v_load_5 => v_load_5_reg_460,
        grp_fu_465_p_din0 => grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_grp_fu_465_p_din0,
        grp_fu_465_p_din1 => grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_grp_fu_465_p_din1,
        grp_fu_465_p_dout0 => grp_fu_465_p2,
        grp_fu_465_p_ce => grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_grp_fu_465_p_ce,
        grp_fu_469_p_din0 => grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_grp_fu_469_p_din0,
        grp_fu_469_p_din1 => grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_grp_fu_469_p_din1,
        grp_fu_469_p_dout0 => grp_fu_469_p2,
        grp_fu_469_p_ce => grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_grp_fu_469_p_ce);

    control_s_axi_U : component attention_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        d_k => d_k,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_continue => ap_continue,
        ap_idle => ap_idle);

    mul_32s_32s_32_2_1_U45 : component attention_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_465_p0,
        din1 => grp_fu_465_p1,
        ce => grp_fu_465_ce,
        dout => grp_fu_465_p2);

    mul_32s_32s_32_2_1_U46 : component attention_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_469_p0,
        din1 => grp_fu_469_p1,
        ce => grp_fu_469_ce,
        dout => grp_fu_469_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_ap_ready = ap_const_logic_1)) then 
                    grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_ap_ready = ap_const_logic_1)) then 
                    grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state1_ignore_call34) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_ap_ready = ap_const_logic_1)) then 
                    grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_ap_ready = ap_const_logic_1)) then 
                    grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                    grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_ap_ready = ap_const_logic_1)) then 
                    grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_rst_n_inv_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_rst_n_inv <= ap_rst_reg_1;
        end if;
    end process;

    ap_rst_reg_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_rst_reg_1 <= ap_rst_reg_2;
        end if;
    end process;

    ap_rst_reg_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
                        ap_rst_reg_2 <= not(ap_rst_n);
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                d_k_read_reg_364 <= d_k;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                v_load_1_reg_418 <= v_Dout_A;
                v_load_reg_413 <= v_Dout_B;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_ap_done = ap_const_logic_1))) then
                v_load_2_reg_433 <= v_Dout_B;
                v_load_3_reg_438 <= v_Dout_A;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                v_load_4_reg_455 <= v_Dout_B;
                v_load_5_reg_460 <= v_Dout_A;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state6, grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_ap_done, ap_CS_fsm_state8, grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_ap_done, grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_ap_done, grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_ap_done, grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state10, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if (((grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state10_blk_assign_proc : process(grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_ap_done)
    begin
        if ((grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state10_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state10_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_ap_done)
    begin
        if ((grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_ap_done)
    begin
        if ((grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_ap_done)
    begin
        if ((grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_ap_done)
    begin
        if ((grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state1_ignore_call34_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call34 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_ap_done, ap_CS_fsm_state10)
    begin
        if (((grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_ap_done, ap_CS_fsm_state10)
    begin
        if (((grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_ap_start <= grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_ap_start_reg;
    grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_ap_start <= grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_ap_start_reg;
    grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_ap_start <= grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_ap_start_reg;
    grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_ap_start <= grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_ap_start_reg;
    grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_ap_start <= grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_ap_start_reg;

    grp_fu_465_ce_assign_proc : process(grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_grp_fu_465_p_ce, grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_grp_fu_465_p_ce, ap_CS_fsm_state4, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            grp_fu_465_ce <= grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_grp_fu_465_p_ce;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_465_ce <= grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_grp_fu_465_p_ce;
        else 
            grp_fu_465_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_465_p0_assign_proc : process(grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_grp_fu_465_p_din0, grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_grp_fu_465_p_din0, ap_CS_fsm_state4, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            grp_fu_465_p0 <= grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_grp_fu_465_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_465_p0 <= grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_grp_fu_465_p_din0;
        else 
            grp_fu_465_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_465_p1_assign_proc : process(grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_grp_fu_465_p_din1, grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_grp_fu_465_p_din1, ap_CS_fsm_state4, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            grp_fu_465_p1 <= grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_grp_fu_465_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_465_p1 <= grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_grp_fu_465_p_din1;
        else 
            grp_fu_465_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_469_ce_assign_proc : process(grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_grp_fu_469_p_ce, grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_grp_fu_469_p_ce, ap_CS_fsm_state4, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            grp_fu_469_ce <= grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_grp_fu_469_p_ce;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_469_ce <= grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_grp_fu_469_p_ce;
        else 
            grp_fu_469_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_469_p0_assign_proc : process(grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_grp_fu_469_p_din0, grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_grp_fu_469_p_din0, ap_CS_fsm_state4, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            grp_fu_469_p0 <= grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_grp_fu_469_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_469_p0 <= grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_grp_fu_469_p_din0;
        else 
            grp_fu_469_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_469_p1_assign_proc : process(grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_grp_fu_469_p_din1, grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_grp_fu_469_p_din1, ap_CS_fsm_state4, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            grp_fu_469_p1 <= grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_grp_fu_469_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_469_p1 <= grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_grp_fu_469_p_din1;
        else 
            grp_fu_469_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    k_Addr_A <= grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_k_Addr_A;
    k_Clk_A <= ap_clk;
    k_Din_A <= ap_const_lv32_0;
    k_EN_A <= grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_k_EN_A;
    k_Rst_A <= ap_rst_n_inv;
    k_WEN_A <= ap_const_lv4_0;

    k_t_address0_assign_proc : process(grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_k_t_address0, grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_k_t_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            k_t_address0 <= grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_k_t_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            k_t_address0 <= grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_k_t_address0;
        else 
            k_t_address0 <= "XXX";
        end if; 
    end process;


    k_t_ce0_assign_proc : process(grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_k_t_ce0, grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_k_t_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            k_t_ce0 <= grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_k_t_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            k_t_ce0 <= grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_k_t_ce0;
        else 
            k_t_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    k_t_ce1_assign_proc : process(grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_k_t_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            k_t_ce1 <= grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_k_t_ce1;
        else 
            k_t_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    k_t_we0_assign_proc : process(grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_k_t_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            k_t_we0 <= grp_attention_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_fu_181_k_t_we0;
        else 
            k_t_we0 <= ap_const_logic_0;
        end if; 
    end process;

    out_r_Addr_A <= grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_out_r_Addr_A;
    out_r_Addr_B <= grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_out_r_Addr_B;
    out_r_Clk_A <= ap_clk;
    out_r_Clk_B <= ap_clk;
    out_r_Din_A <= grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_out_r_Din_A;
    out_r_Din_B <= grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_out_r_Din_B;
    out_r_EN_A <= grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_out_r_EN_A;
    out_r_EN_B <= grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_out_r_EN_B;
    out_r_Rst_A <= ap_rst_n_inv;
    out_r_Rst_B <= ap_rst_n_inv;
    out_r_WEN_A <= grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_out_r_WEN_A;
    out_r_WEN_B <= grp_attention_Pipeline_VITIS_LOOP_8_1_fu_226_out_r_WEN_B;
    q_Addr_A <= grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_q_Addr_A;
    q_Addr_B <= grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_q_Addr_B;
    q_Clk_A <= ap_clk;
    q_Clk_B <= ap_clk;
    q_Din_A <= ap_const_lv32_0;
    q_Din_B <= ap_const_lv32_0;
    q_EN_A <= grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_q_EN_A;
    q_EN_B <= grp_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3_fu_189_q_EN_B;
    q_Rst_A <= ap_rst_n_inv;
    q_Rst_B <= ap_rst_n_inv;
    q_WEN_A <= ap_const_lv4_0;
    q_WEN_B <= ap_const_lv4_0;
    v_Addr_A <= v_Addr_A_local;
    v_Addr_A_local <= std_logic_vector(shift_left(unsigned(v_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));

    v_Addr_A_orig_assign_proc : process(ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            v_Addr_A_orig <= ap_const_lv64_5(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            v_Addr_A_orig <= ap_const_lv64_4(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            v_Addr_A_orig <= ap_const_lv64_3(32 - 1 downto 0);
        else 
            v_Addr_A_orig <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    v_Addr_B <= v_Addr_B_local;
    v_Addr_B_local <= std_logic_vector(shift_left(unsigned(v_Addr_B_orig),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));

    v_Addr_B_orig_assign_proc : process(ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            v_Addr_B_orig <= ap_const_lv64_2(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            v_Addr_B_orig <= ap_const_lv64_1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            v_Addr_B_orig <= ap_const_lv64_0(32 - 1 downto 0);
        else 
            v_Addr_B_orig <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    v_Clk_A <= ap_clk;
    v_Clk_B <= ap_clk;
    v_Din_A <= ap_const_lv32_0;
    v_Din_B <= ap_const_lv32_0;
    v_EN_A <= v_EN_A_local;

    v_EN_A_local_assign_proc : process(ap_CS_fsm_state6, grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_ap_done, ap_CS_fsm_state7, ap_CS_fsm_state8, grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_ap_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or ((ap_const_logic_1 = ap_CS_fsm_state8) and (grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_ap_done = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_ap_done = ap_const_logic_1)))) then 
            v_EN_A_local <= ap_const_logic_1;
        else 
            v_EN_A_local <= ap_const_logic_0;
        end if; 
    end process;

    v_EN_B <= v_EN_B_local;

    v_EN_B_local_assign_proc : process(ap_CS_fsm_state6, grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_ap_done, ap_CS_fsm_state7, ap_CS_fsm_state8, grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_ap_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or ((ap_const_logic_1 = ap_CS_fsm_state8) and (grp_attention_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_214_ap_done = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2_fu_200_ap_done = ap_const_logic_1)))) then 
            v_EN_B_local <= ap_const_logic_1;
        else 
            v_EN_B_local <= ap_const_logic_0;
        end if; 
    end process;

    v_Rst_A <= ap_rst_n_inv;
    v_Rst_B <= ap_rst_n_inv;
    v_WEN_A <= ap_const_lv4_0;
    v_WEN_B <= ap_const_lv4_0;
end behav;
