-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity attention_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    qk_102_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    qk_91_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    qk_124_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    qk_113_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    d_k : IN STD_LOGIC_VECTOR (31 downto 0);
    qk_scaled_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    qk_scaled_3_out_ap_vld : OUT STD_LOGIC;
    qk_scaled_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    qk_scaled_2_out_ap_vld : OUT STD_LOGIC;
    qk_scaled_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    qk_scaled_1_out_ap_vld : OUT STD_LOGIC;
    qk_scaled_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    qk_scaled_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of attention_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter18 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter19 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter20 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter21 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter22 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter23 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter24 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter25 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter26 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter27 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter28 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter29 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter30 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter31 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter32 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter33 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter34 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter35 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln25_fu_158_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln25_reg_447 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter24_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter26_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter27_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter28_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter29_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter30_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter31_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter32_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_447_pp0_iter33_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_fu_212_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451 : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter24_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter26_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter27_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter28_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter29_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter30_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter31_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter32_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter33_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond58_reg_451_pp0_iter34_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_fu_260_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter24_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter26_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter27_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter28_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter29_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter30_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter31_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter32_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter33_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_reg_464_pp0_iter34_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal j_fu_54 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal select_ln26_fu_266_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_load : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal qk_scaled_fu_58 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal qk_scaled_4_fu_350_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter15_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter16_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter17_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter18_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter19_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter20_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter21_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter22_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter23_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter24_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter25_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter26_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter27_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter28_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter29_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter30_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter31_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter32_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter33_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter34_reg : STD_LOGIC;
    signal qk_scaled_1_fu_62 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal qk_scaled_5_fu_343_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal qk_scaled_2_fu_66 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal qk_scaled_6_fu_336_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal qk_scaled_3_fu_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal qk_scaled_7_fu_329_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_fu_74 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal select_ln25_fu_204_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_i_load : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_flatten41_fu_78 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal add_ln25_1_fu_164_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sig_allocacmp_indvar_flatten41_load : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal icmp_ln26_fu_186_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln25_fu_176_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln24_fu_192_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln25_fu_180_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal and_ln24_fu_198_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_218_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln27_5_fu_232_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln27_4_fu_224_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_248_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln27_fu_254_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_248_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln27_2_fu_315_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln27_3_fu_322_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln27_fu_301_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln27_1_fu_308_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component attention_sdiv_32ns_32ns_32_36_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component attention_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sdiv_32ns_32ns_32_36_1_U9 : component attention_sdiv_32ns_32ns_32_36_1
    generic map (
        ID => 1,
        NUM_STAGE => 36,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_248_p0,
        din1 => d_k,
        ce => ap_const_logic_1,
        dout => grp_fu_248_p2);

    flow_control_loop_pipe_sequential_init_U : component attention_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter34_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter18_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter18 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter19_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter19 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter20_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter20 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter21_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter21 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter22_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter22 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter23_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter23 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter24_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter24 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter25_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter25 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter26_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter26 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter27_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter27 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter28_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter28 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter29_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter29 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter30_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter30 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter31_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter31 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter32_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter32 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter33_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter33 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter34_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter34 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter35_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter35 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter35 <= ap_enable_reg_pp0_iter34;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    i_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln25_fu_158_p2 = ap_const_lv1_0))) then 
                    i_fu_74 <= select_ln25_fu_204_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_74 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten41_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln25_fu_158_p2 = ap_const_lv1_0))) then 
                    indvar_flatten41_fu_78 <= add_ln25_1_fu_164_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten41_fu_78 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_54_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln25_fu_158_p2 = ap_const_lv1_0))) then 
                    j_fu_54 <= select_ln26_fu_266_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_54 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
                ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
                ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
                ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
                ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
                ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
                ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
                ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
                ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
                ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
                ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
                ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
                ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
                ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
                ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
                ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
                ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
                ap_loop_exit_ready_pp0_iter31_reg <= ap_loop_exit_ready_pp0_iter30_reg;
                ap_loop_exit_ready_pp0_iter32_reg <= ap_loop_exit_ready_pp0_iter31_reg;
                ap_loop_exit_ready_pp0_iter33_reg <= ap_loop_exit_ready_pp0_iter32_reg;
                ap_loop_exit_ready_pp0_iter34_reg <= ap_loop_exit_ready_pp0_iter33_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                cond58_reg_451_pp0_iter10_reg <= cond58_reg_451_pp0_iter9_reg;
                cond58_reg_451_pp0_iter11_reg <= cond58_reg_451_pp0_iter10_reg;
                cond58_reg_451_pp0_iter12_reg <= cond58_reg_451_pp0_iter11_reg;
                cond58_reg_451_pp0_iter13_reg <= cond58_reg_451_pp0_iter12_reg;
                cond58_reg_451_pp0_iter14_reg <= cond58_reg_451_pp0_iter13_reg;
                cond58_reg_451_pp0_iter15_reg <= cond58_reg_451_pp0_iter14_reg;
                cond58_reg_451_pp0_iter16_reg <= cond58_reg_451_pp0_iter15_reg;
                cond58_reg_451_pp0_iter17_reg <= cond58_reg_451_pp0_iter16_reg;
                cond58_reg_451_pp0_iter18_reg <= cond58_reg_451_pp0_iter17_reg;
                cond58_reg_451_pp0_iter19_reg <= cond58_reg_451_pp0_iter18_reg;
                cond58_reg_451_pp0_iter20_reg <= cond58_reg_451_pp0_iter19_reg;
                cond58_reg_451_pp0_iter21_reg <= cond58_reg_451_pp0_iter20_reg;
                cond58_reg_451_pp0_iter22_reg <= cond58_reg_451_pp0_iter21_reg;
                cond58_reg_451_pp0_iter23_reg <= cond58_reg_451_pp0_iter22_reg;
                cond58_reg_451_pp0_iter24_reg <= cond58_reg_451_pp0_iter23_reg;
                cond58_reg_451_pp0_iter25_reg <= cond58_reg_451_pp0_iter24_reg;
                cond58_reg_451_pp0_iter26_reg <= cond58_reg_451_pp0_iter25_reg;
                cond58_reg_451_pp0_iter27_reg <= cond58_reg_451_pp0_iter26_reg;
                cond58_reg_451_pp0_iter28_reg <= cond58_reg_451_pp0_iter27_reg;
                cond58_reg_451_pp0_iter29_reg <= cond58_reg_451_pp0_iter28_reg;
                cond58_reg_451_pp0_iter2_reg <= cond58_reg_451_pp0_iter1_reg;
                cond58_reg_451_pp0_iter30_reg <= cond58_reg_451_pp0_iter29_reg;
                cond58_reg_451_pp0_iter31_reg <= cond58_reg_451_pp0_iter30_reg;
                cond58_reg_451_pp0_iter32_reg <= cond58_reg_451_pp0_iter31_reg;
                cond58_reg_451_pp0_iter33_reg <= cond58_reg_451_pp0_iter32_reg;
                cond58_reg_451_pp0_iter34_reg <= cond58_reg_451_pp0_iter33_reg;
                cond58_reg_451_pp0_iter3_reg <= cond58_reg_451_pp0_iter2_reg;
                cond58_reg_451_pp0_iter4_reg <= cond58_reg_451_pp0_iter3_reg;
                cond58_reg_451_pp0_iter5_reg <= cond58_reg_451_pp0_iter4_reg;
                cond58_reg_451_pp0_iter6_reg <= cond58_reg_451_pp0_iter5_reg;
                cond58_reg_451_pp0_iter7_reg <= cond58_reg_451_pp0_iter6_reg;
                cond58_reg_451_pp0_iter8_reg <= cond58_reg_451_pp0_iter7_reg;
                cond58_reg_451_pp0_iter9_reg <= cond58_reg_451_pp0_iter8_reg;
                icmp_ln25_reg_447_pp0_iter10_reg <= icmp_ln25_reg_447_pp0_iter9_reg;
                icmp_ln25_reg_447_pp0_iter11_reg <= icmp_ln25_reg_447_pp0_iter10_reg;
                icmp_ln25_reg_447_pp0_iter12_reg <= icmp_ln25_reg_447_pp0_iter11_reg;
                icmp_ln25_reg_447_pp0_iter13_reg <= icmp_ln25_reg_447_pp0_iter12_reg;
                icmp_ln25_reg_447_pp0_iter14_reg <= icmp_ln25_reg_447_pp0_iter13_reg;
                icmp_ln25_reg_447_pp0_iter15_reg <= icmp_ln25_reg_447_pp0_iter14_reg;
                icmp_ln25_reg_447_pp0_iter16_reg <= icmp_ln25_reg_447_pp0_iter15_reg;
                icmp_ln25_reg_447_pp0_iter17_reg <= icmp_ln25_reg_447_pp0_iter16_reg;
                icmp_ln25_reg_447_pp0_iter18_reg <= icmp_ln25_reg_447_pp0_iter17_reg;
                icmp_ln25_reg_447_pp0_iter19_reg <= icmp_ln25_reg_447_pp0_iter18_reg;
                icmp_ln25_reg_447_pp0_iter20_reg <= icmp_ln25_reg_447_pp0_iter19_reg;
                icmp_ln25_reg_447_pp0_iter21_reg <= icmp_ln25_reg_447_pp0_iter20_reg;
                icmp_ln25_reg_447_pp0_iter22_reg <= icmp_ln25_reg_447_pp0_iter21_reg;
                icmp_ln25_reg_447_pp0_iter23_reg <= icmp_ln25_reg_447_pp0_iter22_reg;
                icmp_ln25_reg_447_pp0_iter24_reg <= icmp_ln25_reg_447_pp0_iter23_reg;
                icmp_ln25_reg_447_pp0_iter25_reg <= icmp_ln25_reg_447_pp0_iter24_reg;
                icmp_ln25_reg_447_pp0_iter26_reg <= icmp_ln25_reg_447_pp0_iter25_reg;
                icmp_ln25_reg_447_pp0_iter27_reg <= icmp_ln25_reg_447_pp0_iter26_reg;
                icmp_ln25_reg_447_pp0_iter28_reg <= icmp_ln25_reg_447_pp0_iter27_reg;
                icmp_ln25_reg_447_pp0_iter29_reg <= icmp_ln25_reg_447_pp0_iter28_reg;
                icmp_ln25_reg_447_pp0_iter2_reg <= icmp_ln25_reg_447_pp0_iter1_reg;
                icmp_ln25_reg_447_pp0_iter30_reg <= icmp_ln25_reg_447_pp0_iter29_reg;
                icmp_ln25_reg_447_pp0_iter31_reg <= icmp_ln25_reg_447_pp0_iter30_reg;
                icmp_ln25_reg_447_pp0_iter32_reg <= icmp_ln25_reg_447_pp0_iter31_reg;
                icmp_ln25_reg_447_pp0_iter33_reg <= icmp_ln25_reg_447_pp0_iter32_reg;
                icmp_ln25_reg_447_pp0_iter3_reg <= icmp_ln25_reg_447_pp0_iter2_reg;
                icmp_ln25_reg_447_pp0_iter4_reg <= icmp_ln25_reg_447_pp0_iter3_reg;
                icmp_ln25_reg_447_pp0_iter5_reg <= icmp_ln25_reg_447_pp0_iter4_reg;
                icmp_ln25_reg_447_pp0_iter6_reg <= icmp_ln25_reg_447_pp0_iter5_reg;
                icmp_ln25_reg_447_pp0_iter7_reg <= icmp_ln25_reg_447_pp0_iter6_reg;
                icmp_ln25_reg_447_pp0_iter8_reg <= icmp_ln25_reg_447_pp0_iter7_reg;
                icmp_ln25_reg_447_pp0_iter9_reg <= icmp_ln25_reg_447_pp0_iter8_reg;
                or_ln27_reg_464_pp0_iter10_reg <= or_ln27_reg_464_pp0_iter9_reg;
                or_ln27_reg_464_pp0_iter11_reg <= or_ln27_reg_464_pp0_iter10_reg;
                or_ln27_reg_464_pp0_iter12_reg <= or_ln27_reg_464_pp0_iter11_reg;
                or_ln27_reg_464_pp0_iter13_reg <= or_ln27_reg_464_pp0_iter12_reg;
                or_ln27_reg_464_pp0_iter14_reg <= or_ln27_reg_464_pp0_iter13_reg;
                or_ln27_reg_464_pp0_iter15_reg <= or_ln27_reg_464_pp0_iter14_reg;
                or_ln27_reg_464_pp0_iter16_reg <= or_ln27_reg_464_pp0_iter15_reg;
                or_ln27_reg_464_pp0_iter17_reg <= or_ln27_reg_464_pp0_iter16_reg;
                or_ln27_reg_464_pp0_iter18_reg <= or_ln27_reg_464_pp0_iter17_reg;
                or_ln27_reg_464_pp0_iter19_reg <= or_ln27_reg_464_pp0_iter18_reg;
                or_ln27_reg_464_pp0_iter20_reg <= or_ln27_reg_464_pp0_iter19_reg;
                or_ln27_reg_464_pp0_iter21_reg <= or_ln27_reg_464_pp0_iter20_reg;
                or_ln27_reg_464_pp0_iter22_reg <= or_ln27_reg_464_pp0_iter21_reg;
                or_ln27_reg_464_pp0_iter23_reg <= or_ln27_reg_464_pp0_iter22_reg;
                or_ln27_reg_464_pp0_iter24_reg <= or_ln27_reg_464_pp0_iter23_reg;
                or_ln27_reg_464_pp0_iter25_reg <= or_ln27_reg_464_pp0_iter24_reg;
                or_ln27_reg_464_pp0_iter26_reg <= or_ln27_reg_464_pp0_iter25_reg;
                or_ln27_reg_464_pp0_iter27_reg <= or_ln27_reg_464_pp0_iter26_reg;
                or_ln27_reg_464_pp0_iter28_reg <= or_ln27_reg_464_pp0_iter27_reg;
                or_ln27_reg_464_pp0_iter29_reg <= or_ln27_reg_464_pp0_iter28_reg;
                or_ln27_reg_464_pp0_iter2_reg <= or_ln27_reg_464_pp0_iter1_reg;
                or_ln27_reg_464_pp0_iter30_reg <= or_ln27_reg_464_pp0_iter29_reg;
                or_ln27_reg_464_pp0_iter31_reg <= or_ln27_reg_464_pp0_iter30_reg;
                or_ln27_reg_464_pp0_iter32_reg <= or_ln27_reg_464_pp0_iter31_reg;
                or_ln27_reg_464_pp0_iter33_reg <= or_ln27_reg_464_pp0_iter32_reg;
                or_ln27_reg_464_pp0_iter34_reg <= or_ln27_reg_464_pp0_iter33_reg;
                or_ln27_reg_464_pp0_iter3_reg <= or_ln27_reg_464_pp0_iter2_reg;
                or_ln27_reg_464_pp0_iter4_reg <= or_ln27_reg_464_pp0_iter3_reg;
                or_ln27_reg_464_pp0_iter5_reg <= or_ln27_reg_464_pp0_iter4_reg;
                or_ln27_reg_464_pp0_iter6_reg <= or_ln27_reg_464_pp0_iter5_reg;
                or_ln27_reg_464_pp0_iter7_reg <= or_ln27_reg_464_pp0_iter6_reg;
                or_ln27_reg_464_pp0_iter8_reg <= or_ln27_reg_464_pp0_iter7_reg;
                or_ln27_reg_464_pp0_iter9_reg <= or_ln27_reg_464_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                cond58_reg_451 <= cond58_fu_212_p2;
                cond58_reg_451_pp0_iter1_reg <= cond58_reg_451;
                icmp_ln25_reg_447 <= icmp_ln25_fu_158_p2;
                icmp_ln25_reg_447_pp0_iter1_reg <= icmp_ln25_reg_447;
                or_ln27_reg_464 <= or_ln27_fu_260_p2;
                or_ln27_reg_464_pp0_iter1_reg <= or_ln27_reg_464;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter35 = ap_const_logic_1))) then
                qk_scaled_1_fu_62 <= qk_scaled_5_fu_343_p3;
                qk_scaled_2_fu_66 <= qk_scaled_6_fu_336_p3;
                qk_scaled_3_fu_70 <= qk_scaled_7_fu_329_p3;
                qk_scaled_fu_58 <= qk_scaled_4_fu_350_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln25_1_fu_164_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten41_load) + unsigned(ap_const_lv3_1));
    add_ln25_fu_180_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_load) + unsigned(ap_const_lv2_1));
    and_ln24_fu_198_p2 <= (xor_ln24_fu_192_p2 and trunc_ln25_fu_176_p1);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln25_fu_158_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln25_fu_158_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter34_reg, ap_done_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter34_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_idle_pp0 = ap_const_logic_1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18, ap_enable_reg_pp0_iter19, ap_enable_reg_pp0_iter20, ap_enable_reg_pp0_iter21, ap_enable_reg_pp0_iter22, ap_enable_reg_pp0_iter23, ap_enable_reg_pp0_iter24, ap_enable_reg_pp0_iter25, ap_enable_reg_pp0_iter26, ap_enable_reg_pp0_iter27, ap_enable_reg_pp0_iter28, ap_enable_reg_pp0_iter29, ap_enable_reg_pp0_iter30, ap_enable_reg_pp0_iter31, ap_enable_reg_pp0_iter32, ap_enable_reg_pp0_iter33, ap_enable_reg_pp0_iter34, ap_enable_reg_pp0_iter35)
    begin
        if (((ap_enable_reg_pp0_iter26 = ap_const_logic_0) and (ap_enable_reg_pp0_iter25 = ap_const_logic_0) and (ap_enable_reg_pp0_iter24 = ap_const_logic_0) and (ap_enable_reg_pp0_iter23 = ap_const_logic_0) and (ap_enable_reg_pp0_iter22 = ap_const_logic_0) and (ap_enable_reg_pp0_iter21 = ap_const_logic_0) and (ap_enable_reg_pp0_iter20 = ap_const_logic_0) and (ap_enable_reg_pp0_iter19 = ap_const_logic_0) and (ap_enable_reg_pp0_iter18 = ap_const_logic_0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = 
    ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter35 = ap_const_logic_0) and (ap_enable_reg_pp0_iter34 = ap_const_logic_0) and (ap_enable_reg_pp0_iter33 = ap_const_logic_0) and (ap_enable_reg_pp0_iter32 = ap_const_logic_0) and (ap_enable_reg_pp0_iter31 = ap_const_logic_0) and (ap_enable_reg_pp0_iter30 = ap_const_logic_0) and (ap_enable_reg_pp0_iter29 = ap_const_logic_0) and (ap_enable_reg_pp0_iter28 = ap_const_logic_0) and (ap_enable_reg_pp0_iter27 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, i_fu_74)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_i_load <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_i_load <= i_fu_74;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten41_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, indvar_flatten41_fu_78)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten41_load <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_indvar_flatten41_load <= indvar_flatten41_fu_78;
        end if; 
    end process;


    ap_sig_allocacmp_j_load_assign_proc : process(ap_CS_fsm_pp0_stage0, j_fu_54, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_j_load <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_j_load <= j_fu_54;
        end if; 
    end process;

    cond58_fu_212_p2 <= "1" when (select_ln25_fu_204_p3 = ap_const_lv2_0) else "0";
    empty_fu_218_p2 <= "1" when (select_ln25_fu_204_p3 = ap_const_lv2_1) else "0";
    grp_fu_248_p0 <= 
        select_ln27_5_fu_232_p3 when (empty_fu_218_p2(0) = '1') else 
        select_ln27_4_fu_224_p3;
    icmp_ln25_fu_158_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten41_load = ap_const_lv3_4) else "0";
    icmp_ln26_fu_186_p2 <= "1" when (ap_sig_allocacmp_j_load = ap_const_lv2_2) else "0";
    or_ln27_fu_260_p2 <= (xor_ln27_fu_254_p2 or icmp_ln26_fu_186_p2);
    qk_scaled_1_out <= qk_scaled_1_fu_62;

    qk_scaled_1_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln25_reg_447_pp0_iter33_reg, ap_loop_exit_ready_pp0_iter34_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter34_reg = ap_const_logic_1) and (icmp_ln25_reg_447_pp0_iter33_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            qk_scaled_1_out_ap_vld <= ap_const_logic_1;
        else 
            qk_scaled_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    qk_scaled_2_out <= qk_scaled_2_fu_66;

    qk_scaled_2_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln25_reg_447_pp0_iter33_reg, ap_loop_exit_ready_pp0_iter34_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter34_reg = ap_const_logic_1) and (icmp_ln25_reg_447_pp0_iter33_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            qk_scaled_2_out_ap_vld <= ap_const_logic_1;
        else 
            qk_scaled_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    qk_scaled_3_out <= qk_scaled_3_fu_70;

    qk_scaled_3_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln25_reg_447_pp0_iter33_reg, ap_loop_exit_ready_pp0_iter34_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter34_reg = ap_const_logic_1) and (icmp_ln25_reg_447_pp0_iter33_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            qk_scaled_3_out_ap_vld <= ap_const_logic_1;
        else 
            qk_scaled_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    qk_scaled_4_fu_350_p3 <= 
        select_ln27_1_fu_308_p3 when (cond58_reg_451_pp0_iter34_reg(0) = '1') else 
        qk_scaled_fu_58;
    qk_scaled_5_fu_343_p3 <= 
        select_ln27_fu_301_p3 when (cond58_reg_451_pp0_iter34_reg(0) = '1') else 
        qk_scaled_1_fu_62;
    qk_scaled_6_fu_336_p3 <= 
        qk_scaled_2_fu_66 when (cond58_reg_451_pp0_iter34_reg(0) = '1') else 
        select_ln27_3_fu_322_p3;
    qk_scaled_7_fu_329_p3 <= 
        qk_scaled_3_fu_70 when (cond58_reg_451_pp0_iter34_reg(0) = '1') else 
        select_ln27_2_fu_315_p3;
    qk_scaled_out <= qk_scaled_fu_58;

    qk_scaled_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln25_reg_447_pp0_iter33_reg, ap_loop_exit_ready_pp0_iter34_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter34_reg = ap_const_logic_1) and (icmp_ln25_reg_447_pp0_iter33_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            qk_scaled_out_ap_vld <= ap_const_logic_1;
        else 
            qk_scaled_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    select_ln25_fu_204_p3 <= 
        add_ln25_fu_180_p2 when (icmp_ln26_fu_186_p2(0) = '1') else 
        ap_sig_allocacmp_i_load;
    select_ln26_fu_266_p3 <= 
        ap_const_lv2_2 when (and_ln24_fu_198_p2(0) = '1') else 
        ap_const_lv2_1;
    select_ln27_1_fu_308_p3 <= 
        grp_fu_248_p2 when (or_ln27_reg_464_pp0_iter34_reg(0) = '1') else 
        qk_scaled_fu_58;
    select_ln27_2_fu_315_p3 <= 
        qk_scaled_3_fu_70 when (or_ln27_reg_464_pp0_iter34_reg(0) = '1') else 
        grp_fu_248_p2;
    select_ln27_3_fu_322_p3 <= 
        grp_fu_248_p2 when (or_ln27_reg_464_pp0_iter34_reg(0) = '1') else 
        qk_scaled_2_fu_66;
    select_ln27_4_fu_224_p3 <= 
        qk_102_reload when (and_ln24_fu_198_p2(0) = '1') else 
        qk_91_reload;
    select_ln27_5_fu_232_p3 <= 
        qk_124_reload when (and_ln24_fu_198_p2(0) = '1') else 
        qk_113_reload;
    select_ln27_fu_301_p3 <= 
        qk_scaled_1_fu_62 when (or_ln27_reg_464_pp0_iter34_reg(0) = '1') else 
        grp_fu_248_p2;
    trunc_ln25_fu_176_p1 <= ap_sig_allocacmp_j_load(1 - 1 downto 0);
    xor_ln24_fu_192_p2 <= (icmp_ln26_fu_186_p2 xor ap_const_lv1_1);
    xor_ln27_fu_254_p2 <= (trunc_ln25_fu_176_p1 xor ap_const_lv1_1);
end behav;
