// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mat_mul_mat_mul,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu50-fsvh2104-2-e,HLS_INPUT_CLOCK=3.333000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.922000,HLS_SYN_LAT=37,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=892,HLS_SYN_LUT=709,HLS_VERSION=2024_2}" *)

module mat_mul (
        ap_clk,
        ap_rst_n,
        in1_Addr_A,
        in1_EN_A,
        in1_WEN_A,
        in1_Din_A,
        in1_Dout_A,
        in1_Clk_A,
        in1_Rst_A,
        in1_Addr_B,
        in1_EN_B,
        in1_WEN_B,
        in1_Din_B,
        in1_Dout_B,
        in1_Clk_B,
        in1_Rst_B,
        in2_Addr_A,
        in2_EN_A,
        in2_WEN_A,
        in2_Din_A,
        in2_Dout_A,
        in2_Clk_A,
        in2_Rst_A,
        in2_Addr_B,
        in2_EN_B,
        in2_WEN_B,
        in2_Din_B,
        in2_Dout_B,
        in2_Clk_B,
        in2_Rst_B,
        out_r_Addr_A,
        out_r_EN_A,
        out_r_WEN_A,
        out_r_Din_A,
        out_r_Dout_A,
        out_r_Clk_A,
        out_r_Rst_A,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output  [31:0] in1_Addr_A;
output   in1_EN_A;
output  [3:0] in1_WEN_A;
output  [31:0] in1_Din_A;
input  [31:0] in1_Dout_A;
output   in1_Clk_A;
output   in1_Rst_A;
output  [31:0] in1_Addr_B;
output   in1_EN_B;
output  [3:0] in1_WEN_B;
output  [31:0] in1_Din_B;
input  [31:0] in1_Dout_B;
output   in1_Clk_B;
output   in1_Rst_B;
output  [31:0] in2_Addr_A;
output   in2_EN_A;
output  [3:0] in2_WEN_A;
output  [31:0] in2_Din_A;
input  [31:0] in2_Dout_A;
output   in2_Clk_A;
output   in2_Rst_A;
output  [31:0] in2_Addr_B;
output   in2_EN_B;
output  [3:0] in2_WEN_B;
output  [31:0] in2_Din_B;
input  [31:0] in2_Dout_B;
output   in2_Clk_B;
output   in2_Rst_B;
output  [31:0] out_r_Addr_A;
output   out_r_EN_A;
output  [3:0] out_r_WEN_A;
output  [31:0] out_r_Din_A;
input  [31:0] out_r_Dout_A;
output   out_r_Clk_A;
output   out_r_Rst_A;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_done;
wire    ap_continue;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln9_fu_441_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg;
reg    ap_block_pp0_stage0_11001;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter2_reg;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter3_reg;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter4_reg;
reg    ap_loop_exit_ready_delayed;
reg   [0:0] icmp_ln108_reg_161;
reg   [0:0] icmp_ln108_reg_161_pp0_iter1_reg;
reg   [0:0] icmp_ln108_reg_161_pp0_iter2_reg;
reg   [0:0] icmp_ln108_reg_161_pp0_iter3_reg;
wire   [0:0] or_ln9_fu_257_p2;
reg   [0:0] or_ln9_reg_552;
reg   [0:0] or_ln9_reg_552_pp0_iter1_reg;
reg   [0:0] or_ln9_reg_552_pp0_iter2_reg;
reg   [0:0] or_ln9_reg_552_pp0_iter3_reg;
wire   [3:0] add_ln16_fu_313_p2;
reg   [3:0] add_ln16_reg_557;
reg   [3:0] add_ln16_reg_557_pp0_iter1_reg;
reg   [3:0] add_ln16_reg_557_pp0_iter2_reg;
reg   [3:0] add_ln16_reg_557_pp0_iter3_reg;
wire   [0:0] tmp_5_fu_401_p3;
reg   [0:0] tmp_5_reg_582;
reg   [0:0] tmp_5_reg_582_pp0_iter1_reg;
reg   [0:0] tmp_5_reg_582_pp0_iter2_reg;
reg   [0:0] tmp_5_reg_582_pp0_iter3_reg;
wire   [0:0] xor_ln12_fu_409_p2;
reg   [0:0] xor_ln12_reg_586;
wire   [0:0] icmp_ln10_fu_435_p2;
reg   [0:0] icmp_ln10_reg_591;
reg   [0:0] icmp_ln9_reg_596;
reg  signed [31:0] in1_load_reg_600;
reg  signed [31:0] in2_load_reg_605;
reg  signed [31:0] in1_load_1_reg_610;
reg  signed [31:0] in2_load_1_reg_615;
wire   [31:0] grp_fu_182_p2;
reg   [31:0] mul_ln14_reg_620;
wire   [31:0] grp_fu_186_p2;
reg   [31:0] mul_ln14_1_reg_625;
reg   [0:0] ap_phi_mux_icmp_ln108_phi_fu_164_p4;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg   [0:0] ap_phi_mux_icmp_ln127_phi_fu_175_p4;
wire   [63:0] zext_ln14_1_fu_329_p1;
wire   [63:0] zext_ln14_3_fu_348_p1;
wire   [63:0] zext_ln14_2_fu_371_p1;
wire   [63:0] zext_ln14_4_fu_390_p1;
wire   [63:0] zext_ln16_1_fu_490_p1;
reg   [4:0] indvar_flatten131_fu_74;
wire   [4:0] add_ln9_1_fu_415_p2;
reg   [4:0] ap_sig_allocacmp_indvar_flatten131_load;
reg   [2:0] i2_fu_78;
wire   [2:0] i_fu_263_p3;
reg   [2:0] ap_sig_allocacmp_i2_load;
reg   [4:0] indvar_flatten3_fu_82;
wire   [4:0] select_ln10_1_fu_427_p3;
reg   [4:0] ap_sig_allocacmp_indvar_flatten3_load;
reg   [2:0] j4_fu_86;
wire   [2:0] j_fu_293_p3;
reg   [2:0] ap_sig_allocacmp_j4_load;
reg   [2:0] k5_fu_90;
wire   [2:0] k_fu_395_p2;
reg   [2:0] ap_sig_allocacmp_k5_load;
reg   [31:0] sum6_fu_94;
wire   [31:0] sum_fu_498_p2;
reg    in1_EN_B_local;
wire   [31:0] in1_Addr_B_local;
wire   [31:0] in1_Addr_B_orig;
reg    in1_EN_A_local;
wire   [31:0] in1_Addr_A_local;
wire   [31:0] in1_Addr_A_orig;
reg    in2_EN_B_local;
wire   [31:0] in2_Addr_B_local;
wire   [31:0] in2_Addr_B_orig;
reg    in2_EN_A_local;
wire   [31:0] in2_Addr_A_local;
wire   [31:0] in2_Addr_A_orig;
reg   [3:0] out_r_WEN_A_local;
reg    out_r_EN_A_local;
wire   [31:0] out_r_Addr_A_local;
wire   [31:0] out_r_Addr_A_orig;
wire   [2:0] add_ln9_fu_235_p2;
wire   [2:0] select_ln9_fu_241_p3;
wire   [2:0] select_ln9_1_fu_249_p3;
wire   [2:0] k_mid2_fu_281_p3;
wire   [2:0] add_ln10_fu_275_p2;
wire   [1:0] trunc_ln10_fu_271_p1;
wire   [3:0] tmp_fu_301_p3;
wire   [3:0] zext_ln16_fu_309_p1;
wire   [3:0] zext_ln14_fu_319_p1;
wire   [3:0] add_ln14_1_fu_323_p2;
wire   [1:0] empty_fu_289_p1;
wire   [3:0] tmp_1_fu_334_p3;
wire   [3:0] add_ln14_2_fu_342_p2;
wire   [0:0] tmp_2_fu_353_p3;
wire   [3:0] tmp_3_fu_361_p4;
wire   [3:0] tmp_4_fu_376_p3;
wire   [3:0] add_ln14_3_fu_384_p2;
wire   [4:0] add_ln10_1_fu_421_p2;
wire   [31:0] select_ln9_2_fu_475_p3;
wire   [31:0] sum_mid2_fu_483_p3;
wire   [31:0] add_ln14_fu_494_p2;
reg    grp_fu_182_ce;
reg    grp_fu_186_ce;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_519;
reg    ap_condition_159;
reg    ap_condition_526;
reg    ap_condition_252;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 indvar_flatten131_fu_74 = 5'd0;
#0 i2_fu_78 = 3'd0;
#0 indvar_flatten3_fu_82 = 5'd0;
#0 j4_fu_86 = 3'd0;
#0 k5_fu_90 = 3'd0;
#0 sum6_fu_94 = 32'd0;
end

mat_mul_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle)
);

mat_mul_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(in2_load_reg_605),
    .din1(in1_load_reg_600),
    .ce(grp_fu_182_ce),
    .dout(grp_fu_182_p2)
);

mat_mul_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U2(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(in2_load_1_reg_615),
    .din1(in1_load_1_reg_610),
    .ce(grp_fu_186_ce),
    .dout(grp_fu_186_p2)
);

mat_mul_flow_control_loop_delay_pipe flow_control_loop_delay_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue),
    .ap_loop_exit_ready_delayed(ap_loop_exit_ready_delayed)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_159)) begin
        i2_fu_78 <= i_fu_263_p3;
    end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
    if ((1'b1 == ap_condition_526)) begin
        icmp_ln108_reg_161 <= icmp_ln10_reg_591;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1))) begin
        icmp_ln108_reg_161 <= 1'd0;
    end
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_159)) begin
    indvar_flatten131_fu_74 <= add_ln9_1_fu_415_p2;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_159)) begin
    indvar_flatten3_fu_82 <= select_ln10_1_fu_427_p3;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_159)) begin
    j4_fu_86 <= j_fu_293_p3;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_159)) begin
    k5_fu_90 <= k_fu_395_p2;
end
end

always @ (posedge ap_clk) begin
if ((1'b0 == ap_block_pp0_stage0_11001)) begin
    if ((1'b1 == ap_condition_252)) begin
        sum6_fu_94 <= 32'd0;
    end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
        sum6_fu_94 <= sum_fu_498_p2;
    end
end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln16_reg_557 <= add_ln16_fu_313_p2;
        add_ln16_reg_557_pp0_iter1_reg <= add_ln16_reg_557;
        ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg <= ap_condition_exit_pp0_iter0_stage0;
        ap_condition_exit_pp0_iter0_stage0_pp0_iter2_reg <= ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln108_reg_161_pp0_iter1_reg <= icmp_ln108_reg_161;
        icmp_ln9_reg_596 <= icmp_ln9_fu_441_p2;
        or_ln9_reg_552 <= or_ln9_fu_257_p2;
        or_ln9_reg_552_pp0_iter1_reg <= or_ln9_reg_552;
        tmp_5_reg_582 <= k_fu_395_p2[32'd2];
        tmp_5_reg_582_pp0_iter1_reg <= tmp_5_reg_582;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln16_reg_557_pp0_iter2_reg <= add_ln16_reg_557_pp0_iter1_reg;
        add_ln16_reg_557_pp0_iter3_reg <= add_ln16_reg_557_pp0_iter2_reg;
        ap_condition_exit_pp0_iter0_stage0_pp0_iter3_reg <= ap_condition_exit_pp0_iter0_stage0_pp0_iter2_reg;
        ap_condition_exit_pp0_iter0_stage0_pp0_iter4_reg <= ap_condition_exit_pp0_iter0_stage0_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln108_reg_161_pp0_iter2_reg <= icmp_ln108_reg_161_pp0_iter1_reg;
        icmp_ln108_reg_161_pp0_iter3_reg <= icmp_ln108_reg_161_pp0_iter2_reg;
        mul_ln14_1_reg_625 <= grp_fu_186_p2;
        mul_ln14_reg_620 <= grp_fu_182_p2;
        or_ln9_reg_552_pp0_iter2_reg <= or_ln9_reg_552_pp0_iter1_reg;
        or_ln9_reg_552_pp0_iter3_reg <= or_ln9_reg_552_pp0_iter2_reg;
        tmp_5_reg_582_pp0_iter2_reg <= tmp_5_reg_582_pp0_iter1_reg;
        tmp_5_reg_582_pp0_iter3_reg <= tmp_5_reg_582_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln10_reg_591 <= icmp_ln10_fu_435_p2;
        xor_ln12_reg_586 <= xor_ln12_fu_409_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in1_load_1_reg_610 <= in1_Dout_A;
        in1_load_reg_600 <= in1_Dout_B;
        in2_load_1_reg_615 <= in2_Dout_A;
        in2_load_reg_605 <= in2_Dout_B;
    end
end

always @ (*) begin
    if (((icmp_ln9_fu_441_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_exit_pp0_iter0_stage0_pp0_iter4_reg))) begin
        ap_loop_exit_ready_delayed = 1'b1;
    end else begin
        ap_loop_exit_ready_delayed = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_519)) begin
            ap_phi_mux_icmp_ln108_phi_fu_164_p4 = icmp_ln10_reg_591;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_icmp_ln108_phi_fu_164_p4 = 1'd0;
        end else begin
            ap_phi_mux_icmp_ln108_phi_fu_164_p4 = icmp_ln10_reg_591;
        end
    end else begin
        ap_phi_mux_icmp_ln108_phi_fu_164_p4 = icmp_ln10_reg_591;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_519)) begin
            ap_phi_mux_icmp_ln127_phi_fu_175_p4 = xor_ln12_reg_586;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_icmp_ln127_phi_fu_175_p4 = 1'd1;
        end else begin
            ap_phi_mux_icmp_ln127_phi_fu_175_p4 = xor_ln12_reg_586;
        end
    end else begin
        ap_phi_mux_icmp_ln127_phi_fu_175_p4 = xor_ln12_reg_586;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i2_load = 3'd0;
    end else begin
        ap_sig_allocacmp_i2_load = i2_fu_78;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten131_load = 5'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten131_load = indvar_flatten131_fu_74;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten3_load = 5'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten3_load = indvar_flatten3_fu_82;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j4_load = 3'd0;
    end else begin
        ap_sig_allocacmp_j4_load = j4_fu_86;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_k5_load = 3'd0;
    end else begin
        ap_sig_allocacmp_k5_load = k5_fu_90;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_182_ce = 1'b1;
    end else begin
        grp_fu_182_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_186_ce = 1'b1;
    end else begin
        grp_fu_186_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in1_EN_A_local = 1'b1;
    end else begin
        in1_EN_A_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in1_EN_B_local = 1'b1;
    end else begin
        in1_EN_B_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in2_EN_A_local = 1'b1;
    end else begin
        in2_EN_A_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in2_EN_B_local = 1'b1;
    end else begin
        in2_EN_B_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        out_r_EN_A_local = 1'b1;
    end else begin
        out_r_EN_A_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_5_reg_582_pp0_iter3_reg == 1'd1))) begin
        out_r_WEN_A_local = 4'd15;
    end else begin
        out_r_WEN_A_local = 4'd0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln10_1_fu_421_p2 = (ap_sig_allocacmp_indvar_flatten3_load + 5'd1);

assign add_ln10_fu_275_p2 = (select_ln9_fu_241_p3 + 3'd1);

assign add_ln14_1_fu_323_p2 = (tmp_fu_301_p3 + zext_ln14_fu_319_p1);

assign add_ln14_2_fu_342_p2 = (tmp_1_fu_334_p3 + zext_ln16_fu_309_p1);

assign add_ln14_3_fu_384_p2 = (tmp_4_fu_376_p3 + zext_ln16_fu_309_p1);

assign add_ln14_fu_494_p2 = (mul_ln14_1_reg_625 + mul_ln14_reg_620);

assign add_ln16_fu_313_p2 = (tmp_fu_301_p3 + zext_ln16_fu_309_p1);

assign add_ln9_1_fu_415_p2 = (ap_sig_allocacmp_indvar_flatten131_load + 5'd1);

assign add_ln9_fu_235_p2 = (ap_sig_allocacmp_i2_load + 3'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_condition_159 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_252 = ((ap_start_int == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_519 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln9_reg_596 == 1'd0));
end

always @ (*) begin
    ap_condition_526 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln9_reg_596 == 1'd0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_fu_289_p1 = k_mid2_fu_281_p3[1:0];

assign i_fu_263_p3 = ((ap_phi_mux_icmp_ln108_phi_fu_164_p4[0:0] == 1'b1) ? add_ln9_fu_235_p2 : ap_sig_allocacmp_i2_load);

assign icmp_ln10_fu_435_p2 = ((select_ln10_1_fu_427_p3 == 5'd8) ? 1'b1 : 1'b0);

assign icmp_ln9_fu_441_p2 = ((ap_sig_allocacmp_indvar_flatten131_load == 5'd31) ? 1'b1 : 1'b0);

assign in1_Addr_A = in1_Addr_A_local;

assign in1_Addr_A_local = in1_Addr_A_orig << 32'd2;

assign in1_Addr_A_orig = zext_ln14_2_fu_371_p1;

assign in1_Addr_B = in1_Addr_B_local;

assign in1_Addr_B_local = in1_Addr_B_orig << 32'd2;

assign in1_Addr_B_orig = zext_ln14_1_fu_329_p1;

assign in1_Clk_A = ap_clk;

assign in1_Clk_B = ap_clk;

assign in1_Din_A = 32'd0;

assign in1_Din_B = 32'd0;

assign in1_EN_A = in1_EN_A_local;

assign in1_EN_B = in1_EN_B_local;

assign in1_Rst_A = ap_rst_n_inv;

assign in1_Rst_B = ap_rst_n_inv;

assign in1_WEN_A = 4'd0;

assign in1_WEN_B = 4'd0;

assign in2_Addr_A = in2_Addr_A_local;

assign in2_Addr_A_local = in2_Addr_A_orig << 32'd2;

assign in2_Addr_A_orig = zext_ln14_4_fu_390_p1;

assign in2_Addr_B = in2_Addr_B_local;

assign in2_Addr_B_local = in2_Addr_B_orig << 32'd2;

assign in2_Addr_B_orig = zext_ln14_3_fu_348_p1;

assign in2_Clk_A = ap_clk;

assign in2_Clk_B = ap_clk;

assign in2_Din_A = 32'd0;

assign in2_Din_B = 32'd0;

assign in2_EN_A = in2_EN_A_local;

assign in2_EN_B = in2_EN_B_local;

assign in2_Rst_A = ap_rst_n_inv;

assign in2_Rst_B = ap_rst_n_inv;

assign in2_WEN_A = 4'd0;

assign in2_WEN_B = 4'd0;

assign j_fu_293_p3 = ((or_ln9_fu_257_p2[0:0] == 1'b1) ? select_ln9_fu_241_p3 : add_ln10_fu_275_p2);

assign k_fu_395_p2 = (k_mid2_fu_281_p3 + 3'd2);

assign k_mid2_fu_281_p3 = ((or_ln9_fu_257_p2[0:0] == 1'b1) ? select_ln9_1_fu_249_p3 : 3'd0);

assign or_ln9_fu_257_p2 = (ap_phi_mux_icmp_ln127_phi_fu_175_p4 | ap_phi_mux_icmp_ln108_phi_fu_164_p4);

assign out_r_Addr_A = out_r_Addr_A_local;

assign out_r_Addr_A_local = out_r_Addr_A_orig << 32'd2;

assign out_r_Addr_A_orig = zext_ln16_1_fu_490_p1;

assign out_r_Clk_A = ap_clk;

assign out_r_Din_A = sum_fu_498_p2;

assign out_r_EN_A = out_r_EN_A_local;

assign out_r_Rst_A = ap_rst_n_inv;

assign out_r_WEN_A = out_r_WEN_A_local;

assign select_ln10_1_fu_427_p3 = ((ap_phi_mux_icmp_ln108_phi_fu_164_p4[0:0] == 1'b1) ? 5'd1 : add_ln10_1_fu_421_p2);

assign select_ln9_1_fu_249_p3 = ((ap_phi_mux_icmp_ln108_phi_fu_164_p4[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_k5_load);

assign select_ln9_2_fu_475_p3 = ((icmp_ln108_reg_161_pp0_iter3_reg[0:0] == 1'b1) ? 32'd0 : sum6_fu_94);

assign select_ln9_fu_241_p3 = ((ap_phi_mux_icmp_ln108_phi_fu_164_p4[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_j4_load);

assign sum_fu_498_p2 = (sum_mid2_fu_483_p3 + add_ln14_fu_494_p2);

assign sum_mid2_fu_483_p3 = ((or_ln9_reg_552_pp0_iter3_reg[0:0] == 1'b1) ? select_ln9_2_fu_475_p3 : 32'd0);

assign tmp_1_fu_334_p3 = {{empty_fu_289_p1}, {2'd0}};

assign tmp_2_fu_353_p3 = k_mid2_fu_281_p3[32'd1];

assign tmp_3_fu_361_p4 = {{{trunc_ln10_fu_271_p1}, {tmp_2_fu_353_p3}}, {1'd1}};

assign tmp_4_fu_376_p3 = {{tmp_2_fu_353_p3}, {3'd4}};

assign tmp_5_fu_401_p3 = k_fu_395_p2[32'd2];

assign tmp_fu_301_p3 = {{trunc_ln10_fu_271_p1}, {2'd0}};

assign trunc_ln10_fu_271_p1 = i_fu_263_p3[1:0];

assign xor_ln12_fu_409_p2 = (tmp_5_fu_401_p3 ^ 1'd1);

assign zext_ln14_1_fu_329_p1 = add_ln14_1_fu_323_p2;

assign zext_ln14_2_fu_371_p1 = tmp_3_fu_361_p4;

assign zext_ln14_3_fu_348_p1 = add_ln14_2_fu_342_p2;

assign zext_ln14_4_fu_390_p1 = add_ln14_3_fu_384_p2;

assign zext_ln14_fu_319_p1 = k_mid2_fu_281_p3;

assign zext_ln16_1_fu_490_p1 = add_ln16_reg_557_pp0_iter3_reg;

assign zext_ln16_fu_309_p1 = j_fu_293_p3;

endmodule //mat_mul
