// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module attention_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        qk_102_reload,
        qk_91_reload,
        qk_124_reload,
        qk_113_reload,
        d_k,
        qk_scaled_3_out,
        qk_scaled_3_out_ap_vld,
        qk_scaled_2_out,
        qk_scaled_2_out_ap_vld,
        qk_scaled_1_out,
        qk_scaled_1_out_ap_vld,
        qk_scaled_out,
        qk_scaled_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] qk_102_reload;
input  [31:0] qk_91_reload;
input  [31:0] qk_124_reload;
input  [31:0] qk_113_reload;
input  [31:0] d_k;
output  [31:0] qk_scaled_3_out;
output   qk_scaled_3_out_ap_vld;
output  [31:0] qk_scaled_2_out;
output   qk_scaled_2_out_ap_vld;
output  [31:0] qk_scaled_1_out;
output   qk_scaled_1_out_ap_vld;
output  [31:0] qk_scaled_out;
output   qk_scaled_out_ap_vld;

reg ap_idle;
reg qk_scaled_3_out_ap_vld;
reg qk_scaled_2_out_ap_vld;
reg qk_scaled_1_out_ap_vld;
reg qk_scaled_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg    ap_enable_reg_pp0_iter30;
reg    ap_enable_reg_pp0_iter31;
reg    ap_enable_reg_pp0_iter32;
reg    ap_enable_reg_pp0_iter33;
reg    ap_enable_reg_pp0_iter34;
reg    ap_enable_reg_pp0_iter35;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln25_fu_158_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln25_reg_447;
reg   [0:0] icmp_ln25_reg_447_pp0_iter1_reg;
reg   [0:0] icmp_ln25_reg_447_pp0_iter2_reg;
reg   [0:0] icmp_ln25_reg_447_pp0_iter3_reg;
reg   [0:0] icmp_ln25_reg_447_pp0_iter4_reg;
reg   [0:0] icmp_ln25_reg_447_pp0_iter5_reg;
reg   [0:0] icmp_ln25_reg_447_pp0_iter6_reg;
reg   [0:0] icmp_ln25_reg_447_pp0_iter7_reg;
reg   [0:0] icmp_ln25_reg_447_pp0_iter8_reg;
reg   [0:0] icmp_ln25_reg_447_pp0_iter9_reg;
reg   [0:0] icmp_ln25_reg_447_pp0_iter10_reg;
reg   [0:0] icmp_ln25_reg_447_pp0_iter11_reg;
reg   [0:0] icmp_ln25_reg_447_pp0_iter12_reg;
reg   [0:0] icmp_ln25_reg_447_pp0_iter13_reg;
reg   [0:0] icmp_ln25_reg_447_pp0_iter14_reg;
reg   [0:0] icmp_ln25_reg_447_pp0_iter15_reg;
reg   [0:0] icmp_ln25_reg_447_pp0_iter16_reg;
reg   [0:0] icmp_ln25_reg_447_pp0_iter17_reg;
reg   [0:0] icmp_ln25_reg_447_pp0_iter18_reg;
reg   [0:0] icmp_ln25_reg_447_pp0_iter19_reg;
reg   [0:0] icmp_ln25_reg_447_pp0_iter20_reg;
reg   [0:0] icmp_ln25_reg_447_pp0_iter21_reg;
reg   [0:0] icmp_ln25_reg_447_pp0_iter22_reg;
reg   [0:0] icmp_ln25_reg_447_pp0_iter23_reg;
reg   [0:0] icmp_ln25_reg_447_pp0_iter24_reg;
reg   [0:0] icmp_ln25_reg_447_pp0_iter25_reg;
reg   [0:0] icmp_ln25_reg_447_pp0_iter26_reg;
reg   [0:0] icmp_ln25_reg_447_pp0_iter27_reg;
reg   [0:0] icmp_ln25_reg_447_pp0_iter28_reg;
reg   [0:0] icmp_ln25_reg_447_pp0_iter29_reg;
reg   [0:0] icmp_ln25_reg_447_pp0_iter30_reg;
reg   [0:0] icmp_ln25_reg_447_pp0_iter31_reg;
reg   [0:0] icmp_ln25_reg_447_pp0_iter32_reg;
reg   [0:0] icmp_ln25_reg_447_pp0_iter33_reg;
wire   [0:0] cond58_fu_212_p2;
reg   [0:0] cond58_reg_451;
reg   [0:0] cond58_reg_451_pp0_iter1_reg;
reg   [0:0] cond58_reg_451_pp0_iter2_reg;
reg   [0:0] cond58_reg_451_pp0_iter3_reg;
reg   [0:0] cond58_reg_451_pp0_iter4_reg;
reg   [0:0] cond58_reg_451_pp0_iter5_reg;
reg   [0:0] cond58_reg_451_pp0_iter6_reg;
reg   [0:0] cond58_reg_451_pp0_iter7_reg;
reg   [0:0] cond58_reg_451_pp0_iter8_reg;
reg   [0:0] cond58_reg_451_pp0_iter9_reg;
reg   [0:0] cond58_reg_451_pp0_iter10_reg;
reg   [0:0] cond58_reg_451_pp0_iter11_reg;
reg   [0:0] cond58_reg_451_pp0_iter12_reg;
reg   [0:0] cond58_reg_451_pp0_iter13_reg;
reg   [0:0] cond58_reg_451_pp0_iter14_reg;
reg   [0:0] cond58_reg_451_pp0_iter15_reg;
reg   [0:0] cond58_reg_451_pp0_iter16_reg;
reg   [0:0] cond58_reg_451_pp0_iter17_reg;
reg   [0:0] cond58_reg_451_pp0_iter18_reg;
reg   [0:0] cond58_reg_451_pp0_iter19_reg;
reg   [0:0] cond58_reg_451_pp0_iter20_reg;
reg   [0:0] cond58_reg_451_pp0_iter21_reg;
reg   [0:0] cond58_reg_451_pp0_iter22_reg;
reg   [0:0] cond58_reg_451_pp0_iter23_reg;
reg   [0:0] cond58_reg_451_pp0_iter24_reg;
reg   [0:0] cond58_reg_451_pp0_iter25_reg;
reg   [0:0] cond58_reg_451_pp0_iter26_reg;
reg   [0:0] cond58_reg_451_pp0_iter27_reg;
reg   [0:0] cond58_reg_451_pp0_iter28_reg;
reg   [0:0] cond58_reg_451_pp0_iter29_reg;
reg   [0:0] cond58_reg_451_pp0_iter30_reg;
reg   [0:0] cond58_reg_451_pp0_iter31_reg;
reg   [0:0] cond58_reg_451_pp0_iter32_reg;
reg   [0:0] cond58_reg_451_pp0_iter33_reg;
reg   [0:0] cond58_reg_451_pp0_iter34_reg;
wire   [0:0] or_ln27_fu_260_p2;
reg   [0:0] or_ln27_reg_464;
reg   [0:0] or_ln27_reg_464_pp0_iter1_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter2_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter3_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter4_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter5_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter6_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter7_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter8_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter9_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter10_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter11_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter12_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter13_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter14_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter15_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter16_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter17_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter18_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter19_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter20_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter21_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter22_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter23_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter24_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter25_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter26_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter27_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter28_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter29_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter30_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter31_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter32_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter33_reg;
reg   [0:0] or_ln27_reg_464_pp0_iter34_reg;
reg   [1:0] j_fu_54;
wire   [1:0] select_ln26_fu_266_p3;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_j_load;
wire    ap_block_pp0_stage0;
reg   [31:0] qk_scaled_fu_58;
wire   [31:0] qk_scaled_4_fu_350_p3;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg    ap_loop_exit_ready_pp0_iter22_reg;
reg    ap_loop_exit_ready_pp0_iter23_reg;
reg    ap_loop_exit_ready_pp0_iter24_reg;
reg    ap_loop_exit_ready_pp0_iter25_reg;
reg    ap_loop_exit_ready_pp0_iter26_reg;
reg    ap_loop_exit_ready_pp0_iter27_reg;
reg    ap_loop_exit_ready_pp0_iter28_reg;
reg    ap_loop_exit_ready_pp0_iter29_reg;
reg    ap_loop_exit_ready_pp0_iter30_reg;
reg    ap_loop_exit_ready_pp0_iter31_reg;
reg    ap_loop_exit_ready_pp0_iter32_reg;
reg    ap_loop_exit_ready_pp0_iter33_reg;
reg    ap_loop_exit_ready_pp0_iter34_reg;
reg   [31:0] qk_scaled_1_fu_62;
wire   [31:0] qk_scaled_5_fu_343_p3;
reg   [31:0] qk_scaled_2_fu_66;
wire   [31:0] qk_scaled_6_fu_336_p3;
reg   [31:0] qk_scaled_3_fu_70;
wire   [31:0] qk_scaled_7_fu_329_p3;
reg   [1:0] i_fu_74;
wire   [1:0] select_ln25_fu_204_p3;
reg   [1:0] ap_sig_allocacmp_i_load;
reg   [2:0] indvar_flatten41_fu_78;
wire   [2:0] add_ln25_1_fu_164_p2;
reg   [2:0] ap_sig_allocacmp_indvar_flatten41_load;
wire    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln26_fu_186_p2;
wire   [0:0] trunc_ln25_fu_176_p1;
wire   [0:0] xor_ln24_fu_192_p2;
wire   [1:0] add_ln25_fu_180_p2;
wire   [0:0] and_ln24_fu_198_p2;
wire   [0:0] empty_fu_218_p2;
wire   [31:0] select_ln27_5_fu_232_p3;
wire   [31:0] select_ln27_4_fu_224_p3;
wire   [31:0] grp_fu_248_p0;
wire   [0:0] xor_ln27_fu_254_p2;
wire   [31:0] grp_fu_248_p2;
wire   [31:0] select_ln27_2_fu_315_p3;
wire   [31:0] select_ln27_3_fu_322_p3;
wire   [31:0] select_ln27_fu_301_p3;
wire   [31:0] select_ln27_1_fu_308_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
#0 ap_enable_reg_pp0_iter30 = 1'b0;
#0 ap_enable_reg_pp0_iter31 = 1'b0;
#0 ap_enable_reg_pp0_iter32 = 1'b0;
#0 ap_enable_reg_pp0_iter33 = 1'b0;
#0 ap_enable_reg_pp0_iter34 = 1'b0;
#0 ap_enable_reg_pp0_iter35 = 1'b0;
#0 j_fu_54 = 2'd0;
#0 qk_scaled_fu_58 = 32'd0;
#0 qk_scaled_1_fu_62 = 32'd0;
#0 qk_scaled_2_fu_66 = 32'd0;
#0 qk_scaled_3_fu_70 = 32'd0;
#0 i_fu_74 = 2'd0;
#0 indvar_flatten41_fu_78 = 3'd0;
#0 ap_done_reg = 1'b0;
end

attention_sdiv_32ns_32ns_32_36_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sdiv_32ns_32ns_32_36_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_248_p0),
    .din1(d_k),
    .ce(1'b1),
    .dout(grp_fu_248_p2)
);

attention_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter34_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter30 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter31 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter32 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter33 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter34 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter35 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter35 <= ap_enable_reg_pp0_iter34;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln25_fu_158_p2 == 1'd0))) begin
            i_fu_74 <= select_ln25_fu_204_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_74 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln25_fu_158_p2 == 1'd0))) begin
            indvar_flatten41_fu_78 <= add_ln25_1_fu_164_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten41_fu_78 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln25_fu_158_p2 == 1'd0))) begin
            j_fu_54 <= select_ln26_fu_266_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_54 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
        ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
        ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
        ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
        ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
        ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
        ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
        ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
        ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
        ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
        ap_loop_exit_ready_pp0_iter31_reg <= ap_loop_exit_ready_pp0_iter30_reg;
        ap_loop_exit_ready_pp0_iter32_reg <= ap_loop_exit_ready_pp0_iter31_reg;
        ap_loop_exit_ready_pp0_iter33_reg <= ap_loop_exit_ready_pp0_iter32_reg;
        ap_loop_exit_ready_pp0_iter34_reg <= ap_loop_exit_ready_pp0_iter33_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        cond58_reg_451_pp0_iter10_reg <= cond58_reg_451_pp0_iter9_reg;
        cond58_reg_451_pp0_iter11_reg <= cond58_reg_451_pp0_iter10_reg;
        cond58_reg_451_pp0_iter12_reg <= cond58_reg_451_pp0_iter11_reg;
        cond58_reg_451_pp0_iter13_reg <= cond58_reg_451_pp0_iter12_reg;
        cond58_reg_451_pp0_iter14_reg <= cond58_reg_451_pp0_iter13_reg;
        cond58_reg_451_pp0_iter15_reg <= cond58_reg_451_pp0_iter14_reg;
        cond58_reg_451_pp0_iter16_reg <= cond58_reg_451_pp0_iter15_reg;
        cond58_reg_451_pp0_iter17_reg <= cond58_reg_451_pp0_iter16_reg;
        cond58_reg_451_pp0_iter18_reg <= cond58_reg_451_pp0_iter17_reg;
        cond58_reg_451_pp0_iter19_reg <= cond58_reg_451_pp0_iter18_reg;
        cond58_reg_451_pp0_iter20_reg <= cond58_reg_451_pp0_iter19_reg;
        cond58_reg_451_pp0_iter21_reg <= cond58_reg_451_pp0_iter20_reg;
        cond58_reg_451_pp0_iter22_reg <= cond58_reg_451_pp0_iter21_reg;
        cond58_reg_451_pp0_iter23_reg <= cond58_reg_451_pp0_iter22_reg;
        cond58_reg_451_pp0_iter24_reg <= cond58_reg_451_pp0_iter23_reg;
        cond58_reg_451_pp0_iter25_reg <= cond58_reg_451_pp0_iter24_reg;
        cond58_reg_451_pp0_iter26_reg <= cond58_reg_451_pp0_iter25_reg;
        cond58_reg_451_pp0_iter27_reg <= cond58_reg_451_pp0_iter26_reg;
        cond58_reg_451_pp0_iter28_reg <= cond58_reg_451_pp0_iter27_reg;
        cond58_reg_451_pp0_iter29_reg <= cond58_reg_451_pp0_iter28_reg;
        cond58_reg_451_pp0_iter2_reg <= cond58_reg_451_pp0_iter1_reg;
        cond58_reg_451_pp0_iter30_reg <= cond58_reg_451_pp0_iter29_reg;
        cond58_reg_451_pp0_iter31_reg <= cond58_reg_451_pp0_iter30_reg;
        cond58_reg_451_pp0_iter32_reg <= cond58_reg_451_pp0_iter31_reg;
        cond58_reg_451_pp0_iter33_reg <= cond58_reg_451_pp0_iter32_reg;
        cond58_reg_451_pp0_iter34_reg <= cond58_reg_451_pp0_iter33_reg;
        cond58_reg_451_pp0_iter3_reg <= cond58_reg_451_pp0_iter2_reg;
        cond58_reg_451_pp0_iter4_reg <= cond58_reg_451_pp0_iter3_reg;
        cond58_reg_451_pp0_iter5_reg <= cond58_reg_451_pp0_iter4_reg;
        cond58_reg_451_pp0_iter6_reg <= cond58_reg_451_pp0_iter5_reg;
        cond58_reg_451_pp0_iter7_reg <= cond58_reg_451_pp0_iter6_reg;
        cond58_reg_451_pp0_iter8_reg <= cond58_reg_451_pp0_iter7_reg;
        cond58_reg_451_pp0_iter9_reg <= cond58_reg_451_pp0_iter8_reg;
        icmp_ln25_reg_447_pp0_iter10_reg <= icmp_ln25_reg_447_pp0_iter9_reg;
        icmp_ln25_reg_447_pp0_iter11_reg <= icmp_ln25_reg_447_pp0_iter10_reg;
        icmp_ln25_reg_447_pp0_iter12_reg <= icmp_ln25_reg_447_pp0_iter11_reg;
        icmp_ln25_reg_447_pp0_iter13_reg <= icmp_ln25_reg_447_pp0_iter12_reg;
        icmp_ln25_reg_447_pp0_iter14_reg <= icmp_ln25_reg_447_pp0_iter13_reg;
        icmp_ln25_reg_447_pp0_iter15_reg <= icmp_ln25_reg_447_pp0_iter14_reg;
        icmp_ln25_reg_447_pp0_iter16_reg <= icmp_ln25_reg_447_pp0_iter15_reg;
        icmp_ln25_reg_447_pp0_iter17_reg <= icmp_ln25_reg_447_pp0_iter16_reg;
        icmp_ln25_reg_447_pp0_iter18_reg <= icmp_ln25_reg_447_pp0_iter17_reg;
        icmp_ln25_reg_447_pp0_iter19_reg <= icmp_ln25_reg_447_pp0_iter18_reg;
        icmp_ln25_reg_447_pp0_iter20_reg <= icmp_ln25_reg_447_pp0_iter19_reg;
        icmp_ln25_reg_447_pp0_iter21_reg <= icmp_ln25_reg_447_pp0_iter20_reg;
        icmp_ln25_reg_447_pp0_iter22_reg <= icmp_ln25_reg_447_pp0_iter21_reg;
        icmp_ln25_reg_447_pp0_iter23_reg <= icmp_ln25_reg_447_pp0_iter22_reg;
        icmp_ln25_reg_447_pp0_iter24_reg <= icmp_ln25_reg_447_pp0_iter23_reg;
        icmp_ln25_reg_447_pp0_iter25_reg <= icmp_ln25_reg_447_pp0_iter24_reg;
        icmp_ln25_reg_447_pp0_iter26_reg <= icmp_ln25_reg_447_pp0_iter25_reg;
        icmp_ln25_reg_447_pp0_iter27_reg <= icmp_ln25_reg_447_pp0_iter26_reg;
        icmp_ln25_reg_447_pp0_iter28_reg <= icmp_ln25_reg_447_pp0_iter27_reg;
        icmp_ln25_reg_447_pp0_iter29_reg <= icmp_ln25_reg_447_pp0_iter28_reg;
        icmp_ln25_reg_447_pp0_iter2_reg <= icmp_ln25_reg_447_pp0_iter1_reg;
        icmp_ln25_reg_447_pp0_iter30_reg <= icmp_ln25_reg_447_pp0_iter29_reg;
        icmp_ln25_reg_447_pp0_iter31_reg <= icmp_ln25_reg_447_pp0_iter30_reg;
        icmp_ln25_reg_447_pp0_iter32_reg <= icmp_ln25_reg_447_pp0_iter31_reg;
        icmp_ln25_reg_447_pp0_iter33_reg <= icmp_ln25_reg_447_pp0_iter32_reg;
        icmp_ln25_reg_447_pp0_iter3_reg <= icmp_ln25_reg_447_pp0_iter2_reg;
        icmp_ln25_reg_447_pp0_iter4_reg <= icmp_ln25_reg_447_pp0_iter3_reg;
        icmp_ln25_reg_447_pp0_iter5_reg <= icmp_ln25_reg_447_pp0_iter4_reg;
        icmp_ln25_reg_447_pp0_iter6_reg <= icmp_ln25_reg_447_pp0_iter5_reg;
        icmp_ln25_reg_447_pp0_iter7_reg <= icmp_ln25_reg_447_pp0_iter6_reg;
        icmp_ln25_reg_447_pp0_iter8_reg <= icmp_ln25_reg_447_pp0_iter7_reg;
        icmp_ln25_reg_447_pp0_iter9_reg <= icmp_ln25_reg_447_pp0_iter8_reg;
        or_ln27_reg_464_pp0_iter10_reg <= or_ln27_reg_464_pp0_iter9_reg;
        or_ln27_reg_464_pp0_iter11_reg <= or_ln27_reg_464_pp0_iter10_reg;
        or_ln27_reg_464_pp0_iter12_reg <= or_ln27_reg_464_pp0_iter11_reg;
        or_ln27_reg_464_pp0_iter13_reg <= or_ln27_reg_464_pp0_iter12_reg;
        or_ln27_reg_464_pp0_iter14_reg <= or_ln27_reg_464_pp0_iter13_reg;
        or_ln27_reg_464_pp0_iter15_reg <= or_ln27_reg_464_pp0_iter14_reg;
        or_ln27_reg_464_pp0_iter16_reg <= or_ln27_reg_464_pp0_iter15_reg;
        or_ln27_reg_464_pp0_iter17_reg <= or_ln27_reg_464_pp0_iter16_reg;
        or_ln27_reg_464_pp0_iter18_reg <= or_ln27_reg_464_pp0_iter17_reg;
        or_ln27_reg_464_pp0_iter19_reg <= or_ln27_reg_464_pp0_iter18_reg;
        or_ln27_reg_464_pp0_iter20_reg <= or_ln27_reg_464_pp0_iter19_reg;
        or_ln27_reg_464_pp0_iter21_reg <= or_ln27_reg_464_pp0_iter20_reg;
        or_ln27_reg_464_pp0_iter22_reg <= or_ln27_reg_464_pp0_iter21_reg;
        or_ln27_reg_464_pp0_iter23_reg <= or_ln27_reg_464_pp0_iter22_reg;
        or_ln27_reg_464_pp0_iter24_reg <= or_ln27_reg_464_pp0_iter23_reg;
        or_ln27_reg_464_pp0_iter25_reg <= or_ln27_reg_464_pp0_iter24_reg;
        or_ln27_reg_464_pp0_iter26_reg <= or_ln27_reg_464_pp0_iter25_reg;
        or_ln27_reg_464_pp0_iter27_reg <= or_ln27_reg_464_pp0_iter26_reg;
        or_ln27_reg_464_pp0_iter28_reg <= or_ln27_reg_464_pp0_iter27_reg;
        or_ln27_reg_464_pp0_iter29_reg <= or_ln27_reg_464_pp0_iter28_reg;
        or_ln27_reg_464_pp0_iter2_reg <= or_ln27_reg_464_pp0_iter1_reg;
        or_ln27_reg_464_pp0_iter30_reg <= or_ln27_reg_464_pp0_iter29_reg;
        or_ln27_reg_464_pp0_iter31_reg <= or_ln27_reg_464_pp0_iter30_reg;
        or_ln27_reg_464_pp0_iter32_reg <= or_ln27_reg_464_pp0_iter31_reg;
        or_ln27_reg_464_pp0_iter33_reg <= or_ln27_reg_464_pp0_iter32_reg;
        or_ln27_reg_464_pp0_iter34_reg <= or_ln27_reg_464_pp0_iter33_reg;
        or_ln27_reg_464_pp0_iter3_reg <= or_ln27_reg_464_pp0_iter2_reg;
        or_ln27_reg_464_pp0_iter4_reg <= or_ln27_reg_464_pp0_iter3_reg;
        or_ln27_reg_464_pp0_iter5_reg <= or_ln27_reg_464_pp0_iter4_reg;
        or_ln27_reg_464_pp0_iter6_reg <= or_ln27_reg_464_pp0_iter5_reg;
        or_ln27_reg_464_pp0_iter7_reg <= or_ln27_reg_464_pp0_iter6_reg;
        or_ln27_reg_464_pp0_iter8_reg <= or_ln27_reg_464_pp0_iter7_reg;
        or_ln27_reg_464_pp0_iter9_reg <= or_ln27_reg_464_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        cond58_reg_451 <= cond58_fu_212_p2;
        cond58_reg_451_pp0_iter1_reg <= cond58_reg_451;
        icmp_ln25_reg_447 <= icmp_ln25_fu_158_p2;
        icmp_ln25_reg_447_pp0_iter1_reg <= icmp_ln25_reg_447;
        or_ln27_reg_464 <= or_ln27_fu_260_p2;
        or_ln27_reg_464_pp0_iter1_reg <= or_ln27_reg_464;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter35 == 1'b1))) begin
        qk_scaled_1_fu_62 <= qk_scaled_5_fu_343_p3;
        qk_scaled_2_fu_66 <= qk_scaled_6_fu_336_p3;
        qk_scaled_3_fu_70 <= qk_scaled_7_fu_329_p3;
        qk_scaled_fu_58 <= qk_scaled_4_fu_350_p3;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln25_fu_158_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter34_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_idle_pp0 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter35 == 1'b0) 
    & (ap_enable_reg_pp0_iter34 == 1'b0) & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_i_load = 2'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_74;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten41_load = 3'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten41_load = indvar_flatten41_fu_78;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_j_load = 2'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_54;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter34_reg == 1'b1) & (icmp_ln25_reg_447_pp0_iter33_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        qk_scaled_1_out_ap_vld = 1'b1;
    end else begin
        qk_scaled_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter34_reg == 1'b1) & (icmp_ln25_reg_447_pp0_iter33_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        qk_scaled_2_out_ap_vld = 1'b1;
    end else begin
        qk_scaled_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter34_reg == 1'b1) & (icmp_ln25_reg_447_pp0_iter33_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        qk_scaled_3_out_ap_vld = 1'b1;
    end else begin
        qk_scaled_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter34_reg == 1'b1) & (icmp_ln25_reg_447_pp0_iter33_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        qk_scaled_out_ap_vld = 1'b1;
    end else begin
        qk_scaled_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln25_1_fu_164_p2 = (ap_sig_allocacmp_indvar_flatten41_load + 3'd1);

assign add_ln25_fu_180_p2 = (ap_sig_allocacmp_i_load + 2'd1);

assign and_ln24_fu_198_p2 = (xor_ln24_fu_192_p2 & trunc_ln25_fu_176_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign cond58_fu_212_p2 = ((select_ln25_fu_204_p3 == 2'd0) ? 1'b1 : 1'b0);

assign empty_fu_218_p2 = ((select_ln25_fu_204_p3 == 2'd1) ? 1'b1 : 1'b0);

assign grp_fu_248_p0 = ((empty_fu_218_p2[0:0] == 1'b1) ? select_ln27_5_fu_232_p3 : select_ln27_4_fu_224_p3);

assign icmp_ln25_fu_158_p2 = ((ap_sig_allocacmp_indvar_flatten41_load == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln26_fu_186_p2 = ((ap_sig_allocacmp_j_load == 2'd2) ? 1'b1 : 1'b0);

assign or_ln27_fu_260_p2 = (xor_ln27_fu_254_p2 | icmp_ln26_fu_186_p2);

assign qk_scaled_1_out = qk_scaled_1_fu_62;

assign qk_scaled_2_out = qk_scaled_2_fu_66;

assign qk_scaled_3_out = qk_scaled_3_fu_70;

assign qk_scaled_4_fu_350_p3 = ((cond58_reg_451_pp0_iter34_reg[0:0] == 1'b1) ? select_ln27_1_fu_308_p3 : qk_scaled_fu_58);

assign qk_scaled_5_fu_343_p3 = ((cond58_reg_451_pp0_iter34_reg[0:0] == 1'b1) ? select_ln27_fu_301_p3 : qk_scaled_1_fu_62);

assign qk_scaled_6_fu_336_p3 = ((cond58_reg_451_pp0_iter34_reg[0:0] == 1'b1) ? qk_scaled_2_fu_66 : select_ln27_3_fu_322_p3);

assign qk_scaled_7_fu_329_p3 = ((cond58_reg_451_pp0_iter34_reg[0:0] == 1'b1) ? qk_scaled_3_fu_70 : select_ln27_2_fu_315_p3);

assign qk_scaled_out = qk_scaled_fu_58;

assign select_ln25_fu_204_p3 = ((icmp_ln26_fu_186_p2[0:0] == 1'b1) ? add_ln25_fu_180_p2 : ap_sig_allocacmp_i_load);

assign select_ln26_fu_266_p3 = ((and_ln24_fu_198_p2[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign select_ln27_1_fu_308_p3 = ((or_ln27_reg_464_pp0_iter34_reg[0:0] == 1'b1) ? grp_fu_248_p2 : qk_scaled_fu_58);

assign select_ln27_2_fu_315_p3 = ((or_ln27_reg_464_pp0_iter34_reg[0:0] == 1'b1) ? qk_scaled_3_fu_70 : grp_fu_248_p2);

assign select_ln27_3_fu_322_p3 = ((or_ln27_reg_464_pp0_iter34_reg[0:0] == 1'b1) ? grp_fu_248_p2 : qk_scaled_2_fu_66);

assign select_ln27_4_fu_224_p3 = ((and_ln24_fu_198_p2[0:0] == 1'b1) ? qk_102_reload : qk_91_reload);

assign select_ln27_5_fu_232_p3 = ((and_ln24_fu_198_p2[0:0] == 1'b1) ? qk_124_reload : qk_113_reload);

assign select_ln27_fu_301_p3 = ((or_ln27_reg_464_pp0_iter34_reg[0:0] == 1'b1) ? qk_scaled_1_fu_62 : grp_fu_248_p2);

assign trunc_ln25_fu_176_p1 = ap_sig_allocacmp_j_load[0:0];

assign xor_ln24_fu_192_p2 = (icmp_ln26_fu_186_p2 ^ 1'd1);

assign xor_ln27_fu_254_p2 = (trunc_ln25_fu_176_p1 ^ 1'd1);

endmodule //attention_attention_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_26_2
