// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module attention_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        q_Addr_A,
        q_EN_A,
        q_WEN_A,
        q_Din_A,
        q_Dout_A,
        q_Addr_B,
        q_EN_B,
        q_WEN_B,
        q_Din_B,
        q_Dout_B,
        k_t_address0,
        k_t_ce0,
        k_t_q0,
        k_t_address1,
        k_t_ce1,
        k_t_q1,
        qk_124_out,
        qk_124_out_ap_vld,
        qk_113_out,
        qk_113_out_ap_vld,
        qk_102_out,
        qk_102_out_ap_vld,
        qk_91_out,
        qk_91_out_ap_vld,
        grp_fu_465_p_din0,
        grp_fu_465_p_din1,
        grp_fu_465_p_dout0,
        grp_fu_465_p_ce,
        grp_fu_469_p_din0,
        grp_fu_469_p_din1,
        grp_fu_469_p_dout0,
        grp_fu_469_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] q_Addr_A;
output   q_EN_A;
output  [3:0] q_WEN_A;
output  [31:0] q_Din_A;
input  [31:0] q_Dout_A;
output  [31:0] q_Addr_B;
output   q_EN_B;
output  [3:0] q_WEN_B;
output  [31:0] q_Din_B;
input  [31:0] q_Dout_B;
output  [2:0] k_t_address0;
output   k_t_ce0;
input  [31:0] k_t_q0;
output  [2:0] k_t_address1;
output   k_t_ce1;
input  [31:0] k_t_q1;
output  [31:0] qk_124_out;
output   qk_124_out_ap_vld;
output  [31:0] qk_113_out;
output   qk_113_out_ap_vld;
output  [31:0] qk_102_out;
output   qk_102_out_ap_vld;
output  [31:0] qk_91_out;
output   qk_91_out_ap_vld;
output  [31:0] grp_fu_465_p_din0;
output  [31:0] grp_fu_465_p_din1;
input  [31:0] grp_fu_465_p_dout0;
output   grp_fu_465_p_ce;
output  [31:0] grp_fu_469_p_din0;
output  [31:0] grp_fu_469_p_din1;
input  [31:0] grp_fu_469_p_dout0;
output   grp_fu_469_p_ce;

reg ap_idle;
reg qk_124_out_ap_vld;
reg qk_113_out_ap_vld;
reg qk_102_out_ap_vld;
reg qk_91_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln8_fu_260_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [0:0] cmp6_new_phi_0_i_reg_208;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln8_reg_900;
reg   [0:0] icmp_ln8_reg_900_pp0_iter1_reg;
reg   [0:0] icmp_ln8_reg_900_pp0_iter2_reg;
reg   [0:0] icmp_ln8_reg_900_pp0_iter3_reg;
reg   [0:0] icmp_ln8_reg_900_pp0_iter4_reg;
wire   [0:0] icmp_ln9_fu_275_p2;
reg   [0:0] icmp_ln9_reg_904;
reg   [0:0] icmp_ln9_reg_904_pp0_iter1_reg;
reg   [0:0] icmp_ln9_reg_904_pp0_iter2_reg;
reg   [0:0] icmp_ln9_reg_904_pp0_iter3_reg;
reg   [0:0] icmp_ln9_reg_904_pp0_iter4_reg;
wire   [0:0] or_ln22_1_fu_345_p2;
reg   [0:0] or_ln22_1_reg_918;
reg   [0:0] or_ln22_1_reg_918_pp0_iter2_reg;
reg   [0:0] or_ln22_1_reg_918_pp0_iter3_reg;
reg   [0:0] or_ln22_1_reg_918_pp0_iter4_reg;
wire   [0:0] cmp6_new_phi_0_i_mid2_fu_377_p2;
reg   [0:0] cmp6_new_phi_0_i_mid2_reg_927;
reg   [0:0] cmp6_new_phi_0_i_mid2_reg_927_pp0_iter2_reg;
reg   [0:0] cmp6_new_phi_0_i_mid2_reg_927_pp0_iter3_reg;
reg   [0:0] cmp6_new_phi_0_i_mid2_reg_927_pp0_iter4_reg;
wire   [0:0] cond_fu_413_p2;
reg   [0:0] cond_reg_933;
reg   [0:0] cond_reg_933_pp0_iter2_reg;
reg   [0:0] cond_reg_933_pp0_iter3_reg;
reg   [0:0] cond_reg_933_pp0_iter4_reg;
wire   [0:0] icmp_ln11_fu_501_p2;
reg   [0:0] icmp_ln11_reg_961;
reg   [0:0] icmp_ln11_reg_961_pp0_iter2_reg;
reg   [0:0] icmp_ln11_reg_961_pp0_iter3_reg;
reg   [0:0] icmp_ln11_reg_961_pp0_iter4_reg;
wire   [0:0] icmp_ln11_1_fu_513_p2;
wire   [0:0] icmp_ln15_fu_519_p2;
reg   [0:0] icmp_ln15_reg_972;
reg   [0:0] icmp_ln15_reg_972_pp0_iter2_reg;
reg   [0:0] icmp_ln15_reg_972_pp0_iter3_reg;
reg   [0:0] icmp_ln15_reg_972_pp0_iter4_reg;
reg  signed [31:0] q_load_reg_980;
reg  signed [31:0] k_t_load_reg_985;
reg  signed [31:0] q_load_1_reg_990;
reg  signed [31:0] k_t_load_1_reg_995;
reg   [31:0] mul_ln13_reg_1000;
reg   [31:0] mul_ln13_1_reg_1005;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_init;
wire   [63:0] zext_ln13_1_fu_429_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln13_2_fu_446_p1;
wire   [63:0] zext_ln13_4_fu_477_p1;
wire   [63:0] zext_ln13_5_fu_496_p1;
reg   [31:0] sum_fu_70;
wire   [31:0] sum_5_fu_664_p3;
reg   [31:0] add_new_phi_0_i_fu_74;
wire   [31:0] qk_9_fu_671_p3;
reg   [2:0] k_fu_78;
wire   [2:0] k_1_fu_507_p2;
reg   [31:0] qk_fu_82;
wire   [31:0] select_ln9_3_fu_633_p3;
reg   [31:0] qk_91_fu_86;
wire   [31:0] qk_8_fu_727_p3;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [31:0] qk_1_fu_90;
wire   [31:0] select_ln9_2_fu_626_p3;
reg   [31:0] qk_102_fu_94;
wire   [31:0] qk_7_fu_720_p3;
reg   [31:0] qk_2_fu_98;
wire   [31:0] select_ln9_1_fu_619_p3;
reg   [31:0] qk_113_fu_102;
wire   [31:0] qk_6_fu_713_p3;
reg   [31:0] qk_3_fu_106;
wire   [31:0] select_ln9_fu_612_p3;
reg   [31:0] qk_124_fu_110;
wire   [31:0] qk_5_fu_706_p3;
reg   [1:0] j_fu_114;
wire   [1:0] select_ln9_4_fu_383_p3;
reg   [3:0] indvar_flatten10_fu_118;
wire   [3:0] select_ln9_5_fu_287_p3;
reg   [3:0] ap_sig_allocacmp_indvar_flatten10_load;
reg   [1:0] i_fu_122;
wire   [1:0] select_ln8_fu_350_p3;
reg   [3:0] indvar_flatten34_fu_126;
wire   [3:0] add_ln8_fu_266_p2;
reg   [3:0] ap_sig_allocacmp_indvar_flatten34_load;
wire    ap_block_pp0_stage0_01001;
reg    q_EN_B_local;
wire   [31:0] q_Addr_B_local;
wire   [31:0] q_Addr_B_orig;
reg    q_EN_A_local;
wire   [31:0] q_Addr_A_local;
wire   [31:0] q_Addr_A_orig;
reg    k_t_ce1_local;
reg    k_t_ce0_local;
wire   [3:0] add_ln9_1_fu_281_p2;
wire   [0:0] exit_cond_1_i1314_fu_339_p2;
wire   [1:0] add_ln8_1_fu_314_p2;
wire   [1:0] select_ln22_4_fu_320_p3;
wire   [2:0] select_ln22_5_fu_327_p3;
wire   [0:0] or_ln22_fu_334_p2;
wire   [0:0] not_exit_cond_1_i13_mid233_fu_371_p2;
wire   [1:0] add_ln9_fu_357_p2;
wire   [0:0] trunc_ln13_fu_391_p1;
wire   [2:0] tmp_fu_395_p3;
wire   [2:0] zext_ln13_fu_403_p1;
wire   [2:0] sub_ln13_fu_407_p2;
wire   [2:0] k_1_mid2_fu_363_p3;
wire   [2:0] add_ln13_fu_423_p2;
wire   [2:0] shl_ln13_fu_434_p2;
wire   [2:0] select_ln9_4_cast_fu_419_p1;
wire   [2:0] add_ln13_1_fu_440_p2;
wire   [0:0] tmp_1_fu_451_p3;
wire   [1:0] or_ln_fu_459_p3;
wire   [2:0] zext_ln13_3_fu_467_p1;
wire   [2:0] add_ln13_2_fu_471_p2;
wire   [2:0] tmp_5_fu_482_p3;
wire   [2:0] add_ln13_3_fu_490_p2;
wire   [31:0] select_ln22_6_fu_598_p3;
wire   [31:0] select_ln22_fu_570_p3;
wire   [31:0] select_ln22_1_fu_577_p3;
wire   [31:0] select_ln22_2_fu_584_p3;
wire   [31:0] select_ln22_3_fu_591_p3;
wire   [31:0] sum_mid2_fu_605_p3;
wire   [31:0] sum_1_fu_640_p2;
wire   [31:0] sum_2_fu_645_p3;
wire   [31:0] sum_4_fu_659_p2;
wire   [31:0] sum_3_fu_652_p3;
wire   [31:0] select_ln15_2_fu_692_p3;
wire   [31:0] select_ln15_3_fu_699_p3;
wire   [31:0] select_ln15_fu_678_p3;
wire   [31:0] select_ln15_1_fu_685_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_703;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 sum_fu_70 = 32'd0;
#0 add_new_phi_0_i_fu_74 = 32'd0;
#0 k_fu_78 = 3'd0;
#0 qk_fu_82 = 32'd0;
#0 qk_91_fu_86 = 32'd0;
#0 qk_1_fu_90 = 32'd0;
#0 qk_102_fu_94 = 32'd0;
#0 qk_2_fu_98 = 32'd0;
#0 qk_113_fu_102 = 32'd0;
#0 qk_3_fu_106 = 32'd0;
#0 qk_124_fu_110 = 32'd0;
#0 j_fu_114 = 2'd0;
#0 indvar_flatten10_fu_118 = 4'd0;
#0 i_fu_122 = 2'd0;
#0 indvar_flatten34_fu_126 = 4'd0;
#0 ap_done_reg = 1'b0;
end

attention_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1))) begin
            cmp6_new_phi_0_i_reg_208 <= 1'd1;
        end else if ((1'b1 == ap_condition_703)) begin
            cmp6_new_phi_0_i_reg_208 <= icmp_ln11_1_fu_513_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_122 <= 2'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln8_reg_900 == 1'd0))) begin
            i_fu_122 <= select_ln8_fu_350_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln8_fu_260_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten10_fu_118 <= select_ln9_5_fu_287_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten10_fu_118 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln8_fu_260_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten34_fu_126 <= add_ln8_fu_266_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten34_fu_126 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_114 <= 2'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln8_reg_900 == 1'd0))) begin
            j_fu_114 <= select_ln9_4_fu_383_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            k_fu_78 <= 3'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln8_reg_900 == 1'd0))) begin
            k_fu_78 <= k_1_fu_507_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            sum_fu_70 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln8_reg_900_pp0_iter4_reg == 1'd0))) begin
            sum_fu_70 <= sum_5_fu_664_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln8_reg_900_pp0_iter4_reg == 1'd0))) begin
        add_new_phi_0_i_fu_74 <= qk_9_fu_671_p3;
        qk_102_fu_94 <= qk_7_fu_720_p3;
        qk_113_fu_102 <= qk_6_fu_713_p3;
        qk_124_fu_110 <= qk_5_fu_706_p3;
        qk_1_fu_90 <= select_ln9_2_fu_626_p3;
        qk_2_fu_98 <= select_ln9_1_fu_619_p3;
        qk_3_fu_106 <= select_ln9_fu_612_p3;
        qk_91_fu_86 <= qk_8_fu_727_p3;
        qk_fu_82 <= select_ln9_3_fu_633_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        cmp6_new_phi_0_i_mid2_reg_927 <= cmp6_new_phi_0_i_mid2_fu_377_p2;
        cond_reg_933 <= cond_fu_413_p2;
        icmp_ln11_reg_961 <= icmp_ln11_fu_501_p2;
        icmp_ln15_reg_972 <= icmp_ln15_fu_519_p2;
        icmp_ln8_reg_900 <= icmp_ln8_fu_260_p2;
        icmp_ln8_reg_900_pp0_iter1_reg <= icmp_ln8_reg_900;
        icmp_ln9_reg_904 <= icmp_ln9_fu_275_p2;
        icmp_ln9_reg_904_pp0_iter1_reg <= icmp_ln9_reg_904;
        or_ln22_1_reg_918 <= or_ln22_1_fu_345_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        cmp6_new_phi_0_i_mid2_reg_927_pp0_iter2_reg <= cmp6_new_phi_0_i_mid2_reg_927;
        cmp6_new_phi_0_i_mid2_reg_927_pp0_iter3_reg <= cmp6_new_phi_0_i_mid2_reg_927_pp0_iter2_reg;
        cmp6_new_phi_0_i_mid2_reg_927_pp0_iter4_reg <= cmp6_new_phi_0_i_mid2_reg_927_pp0_iter3_reg;
        cond_reg_933_pp0_iter2_reg <= cond_reg_933;
        cond_reg_933_pp0_iter3_reg <= cond_reg_933_pp0_iter2_reg;
        cond_reg_933_pp0_iter4_reg <= cond_reg_933_pp0_iter3_reg;
        icmp_ln11_reg_961_pp0_iter2_reg <= icmp_ln11_reg_961;
        icmp_ln11_reg_961_pp0_iter3_reg <= icmp_ln11_reg_961_pp0_iter2_reg;
        icmp_ln11_reg_961_pp0_iter4_reg <= icmp_ln11_reg_961_pp0_iter3_reg;
        icmp_ln15_reg_972_pp0_iter2_reg <= icmp_ln15_reg_972;
        icmp_ln15_reg_972_pp0_iter3_reg <= icmp_ln15_reg_972_pp0_iter2_reg;
        icmp_ln15_reg_972_pp0_iter4_reg <= icmp_ln15_reg_972_pp0_iter3_reg;
        icmp_ln8_reg_900_pp0_iter2_reg <= icmp_ln8_reg_900_pp0_iter1_reg;
        icmp_ln8_reg_900_pp0_iter3_reg <= icmp_ln8_reg_900_pp0_iter2_reg;
        icmp_ln8_reg_900_pp0_iter4_reg <= icmp_ln8_reg_900_pp0_iter3_reg;
        icmp_ln9_reg_904_pp0_iter2_reg <= icmp_ln9_reg_904_pp0_iter1_reg;
        icmp_ln9_reg_904_pp0_iter3_reg <= icmp_ln9_reg_904_pp0_iter2_reg;
        icmp_ln9_reg_904_pp0_iter4_reg <= icmp_ln9_reg_904_pp0_iter3_reg;
        mul_ln13_1_reg_1005 <= grp_fu_469_p_dout0;
        mul_ln13_reg_1000 <= grp_fu_465_p_dout0;
        or_ln22_1_reg_918_pp0_iter2_reg <= or_ln22_1_reg_918;
        or_ln22_1_reg_918_pp0_iter3_reg <= or_ln22_1_reg_918_pp0_iter2_reg;
        or_ln22_1_reg_918_pp0_iter4_reg <= or_ln22_1_reg_918_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        k_t_load_1_reg_995 <= k_t_q0;
        k_t_load_reg_985 <= k_t_q1;
        q_load_1_reg_990 <= q_Dout_A;
        q_load_reg_980 <= q_Dout_B;
    end
end

always @ (*) begin
    if (((icmp_ln8_fu_260_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln8_reg_900 == 1'd1))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten10_load = 4'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten10_load = indvar_flatten10_fu_118;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten34_load = 4'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten34_load = indvar_flatten34_fu_126;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_t_ce0_local = 1'b1;
    end else begin
        k_t_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_t_ce1_local = 1'b1;
    end else begin
        k_t_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        q_EN_A_local = 1'b1;
    end else begin
        q_EN_A_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        q_EN_B_local = 1'b1;
    end else begin
        q_EN_B_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln8_reg_900_pp0_iter3_reg == 1'd1))) begin
        qk_102_out_ap_vld = 1'b1;
    end else begin
        qk_102_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln8_reg_900_pp0_iter3_reg == 1'd1))) begin
        qk_113_out_ap_vld = 1'b1;
    end else begin
        qk_113_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln8_reg_900_pp0_iter3_reg == 1'd1))) begin
        qk_124_out_ap_vld = 1'b1;
    end else begin
        qk_124_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln8_reg_900_pp0_iter3_reg == 1'd1))) begin
        qk_91_out_ap_vld = 1'b1;
    end else begin
        qk_91_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln13_1_fu_440_p2 = (shl_ln13_fu_434_p2 + select_ln9_4_cast_fu_419_p1);

assign add_ln13_2_fu_471_p2 = (sub_ln13_fu_407_p2 + zext_ln13_3_fu_467_p1);

assign add_ln13_3_fu_490_p2 = (tmp_5_fu_482_p3 + select_ln9_4_cast_fu_419_p1);

assign add_ln13_fu_423_p2 = (sub_ln13_fu_407_p2 + k_1_mid2_fu_363_p3);

assign add_ln8_1_fu_314_p2 = (i_fu_122 + 2'd1);

assign add_ln8_fu_266_p2 = (ap_sig_allocacmp_indvar_flatten34_load + 4'd1);

assign add_ln9_1_fu_281_p2 = (ap_sig_allocacmp_indvar_flatten10_load + 4'd1);

assign add_ln9_fu_357_p2 = (select_ln22_4_fu_320_p3 + 2'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_703 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln8_reg_900 == 1'd0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign cmp6_new_phi_0_i_mid2_fu_377_p2 = (or_ln22_fu_334_p2 | not_exit_cond_1_i13_mid233_fu_371_p2);

assign cond_fu_413_p2 = ((select_ln8_fu_350_p3 == 2'd0) ? 1'b1 : 1'b0);

assign exit_cond_1_i1314_fu_339_p2 = ((k_fu_78 < 3'd3) ? 1'b1 : 1'b0);

assign grp_fu_465_p_ce = 1'b1;

assign grp_fu_465_p_din0 = k_t_load_reg_985;

assign grp_fu_465_p_din1 = q_load_reg_980;

assign grp_fu_469_p_ce = 1'b1;

assign grp_fu_469_p_din0 = k_t_load_1_reg_995;

assign grp_fu_469_p_din1 = q_load_1_reg_990;

assign icmp_ln11_1_fu_513_p2 = ((k_1_fu_507_p2 < 3'd3) ? 1'b1 : 1'b0);

assign icmp_ln11_fu_501_p2 = ((or_ln_fu_459_p3 != 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln15_fu_519_p2 = ((select_ln9_4_fu_383_p3 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln8_fu_260_p2 = ((ap_sig_allocacmp_indvar_flatten34_load == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln9_fu_275_p2 = ((ap_sig_allocacmp_indvar_flatten10_load == 4'd4) ? 1'b1 : 1'b0);

assign k_1_fu_507_p2 = (k_1_mid2_fu_363_p3 + 3'd2);

assign k_1_mid2_fu_363_p3 = ((or_ln22_1_fu_345_p2[0:0] == 1'b1) ? select_ln22_5_fu_327_p3 : 3'd0);

assign k_t_address0 = zext_ln13_5_fu_496_p1;

assign k_t_address1 = zext_ln13_2_fu_446_p1;

assign k_t_ce0 = k_t_ce0_local;

assign k_t_ce1 = k_t_ce1_local;

assign not_exit_cond_1_i13_mid233_fu_371_p2 = (or_ln22_1_fu_345_p2 ^ 1'd1);

assign or_ln22_1_fu_345_p2 = (icmp_ln9_reg_904 | exit_cond_1_i1314_fu_339_p2);

assign or_ln22_fu_334_p2 = (icmp_ln9_reg_904 | cmp6_new_phi_0_i_reg_208);

assign or_ln_fu_459_p3 = {{tmp_1_fu_451_p3}, {1'd1}};

assign q_Addr_A = q_Addr_A_local;

assign q_Addr_A_local = q_Addr_A_orig << 32'd2;

assign q_Addr_A_orig = zext_ln13_4_fu_477_p1;

assign q_Addr_B = q_Addr_B_local;

assign q_Addr_B_local = q_Addr_B_orig << 32'd2;

assign q_Addr_B_orig = zext_ln13_1_fu_429_p1;

assign q_Din_A = 32'd0;

assign q_Din_B = 32'd0;

assign q_EN_A = q_EN_A_local;

assign q_EN_B = q_EN_B_local;

assign q_WEN_A = 4'd0;

assign q_WEN_B = 4'd0;

assign qk_102_out = qk_102_fu_94;

assign qk_113_out = qk_113_fu_102;

assign qk_124_out = qk_124_fu_110;

assign qk_5_fu_706_p3 = ((cond_reg_933_pp0_iter4_reg[0:0] == 1'b1) ? select_ln9_fu_612_p3 : select_ln15_2_fu_692_p3);

assign qk_6_fu_713_p3 = ((cond_reg_933_pp0_iter4_reg[0:0] == 1'b1) ? select_ln9_1_fu_619_p3 : select_ln15_3_fu_699_p3);

assign qk_7_fu_720_p3 = ((cond_reg_933_pp0_iter4_reg[0:0] == 1'b1) ? select_ln15_fu_678_p3 : select_ln9_2_fu_626_p3);

assign qk_8_fu_727_p3 = ((cond_reg_933_pp0_iter4_reg[0:0] == 1'b1) ? select_ln15_1_fu_685_p3 : select_ln9_3_fu_633_p3);

assign qk_91_out = qk_91_fu_86;

assign qk_9_fu_671_p3 = ((icmp_ln11_reg_961_pp0_iter4_reg[0:0] == 1'b1) ? sum_4_fu_659_p2 : sum_3_fu_652_p3);

assign select_ln15_1_fu_685_p3 = ((icmp_ln15_reg_972_pp0_iter4_reg[0:0] == 1'b1) ? qk_9_fu_671_p3 : select_ln9_3_fu_633_p3);

assign select_ln15_2_fu_692_p3 = ((icmp_ln15_reg_972_pp0_iter4_reg[0:0] == 1'b1) ? select_ln9_fu_612_p3 : qk_9_fu_671_p3);

assign select_ln15_3_fu_699_p3 = ((icmp_ln15_reg_972_pp0_iter4_reg[0:0] == 1'b1) ? qk_9_fu_671_p3 : select_ln9_1_fu_619_p3);

assign select_ln15_fu_678_p3 = ((icmp_ln15_reg_972_pp0_iter4_reg[0:0] == 1'b1) ? select_ln9_2_fu_626_p3 : qk_9_fu_671_p3);

assign select_ln22_1_fu_577_p3 = ((icmp_ln9_reg_904_pp0_iter4_reg[0:0] == 1'b1) ? qk_113_fu_102 : qk_2_fu_98);

assign select_ln22_2_fu_584_p3 = ((icmp_ln9_reg_904_pp0_iter4_reg[0:0] == 1'b1) ? qk_102_fu_94 : qk_1_fu_90);

assign select_ln22_3_fu_591_p3 = ((icmp_ln9_reg_904_pp0_iter4_reg[0:0] == 1'b1) ? qk_91_fu_86 : qk_fu_82);

assign select_ln22_4_fu_320_p3 = ((icmp_ln9_reg_904[0:0] == 1'b1) ? 2'd0 : j_fu_114);

assign select_ln22_5_fu_327_p3 = ((icmp_ln9_reg_904[0:0] == 1'b1) ? 3'd0 : k_fu_78);

assign select_ln22_6_fu_598_p3 = ((icmp_ln9_reg_904_pp0_iter4_reg[0:0] == 1'b1) ? 32'd0 : sum_fu_70);

assign select_ln22_fu_570_p3 = ((icmp_ln9_reg_904_pp0_iter4_reg[0:0] == 1'b1) ? qk_124_fu_110 : qk_3_fu_106);

assign select_ln8_fu_350_p3 = ((icmp_ln9_reg_904[0:0] == 1'b1) ? add_ln8_1_fu_314_p2 : i_fu_122);

assign select_ln9_1_fu_619_p3 = ((or_ln22_1_reg_918_pp0_iter4_reg[0:0] == 1'b1) ? select_ln22_1_fu_577_p3 : qk_113_fu_102);

assign select_ln9_2_fu_626_p3 = ((or_ln22_1_reg_918_pp0_iter4_reg[0:0] == 1'b1) ? select_ln22_2_fu_584_p3 : qk_102_fu_94);

assign select_ln9_3_fu_633_p3 = ((or_ln22_1_reg_918_pp0_iter4_reg[0:0] == 1'b1) ? select_ln22_3_fu_591_p3 : qk_91_fu_86);

assign select_ln9_4_cast_fu_419_p1 = select_ln9_4_fu_383_p3;

assign select_ln9_4_fu_383_p3 = ((or_ln22_1_fu_345_p2[0:0] == 1'b1) ? select_ln22_4_fu_320_p3 : add_ln9_fu_357_p2);

assign select_ln9_5_fu_287_p3 = ((icmp_ln9_fu_275_p2[0:0] == 1'b1) ? 4'd1 : add_ln9_1_fu_281_p2);

assign select_ln9_fu_612_p3 = ((or_ln22_1_reg_918_pp0_iter4_reg[0:0] == 1'b1) ? select_ln22_fu_570_p3 : qk_124_fu_110);

assign shl_ln13_fu_434_p2 = k_1_mid2_fu_363_p3 << 3'd1;

assign sub_ln13_fu_407_p2 = (tmp_fu_395_p3 - zext_ln13_fu_403_p1);

assign sum_1_fu_640_p2 = (mul_ln13_reg_1000 + sum_mid2_fu_605_p3);

assign sum_2_fu_645_p3 = ((cmp6_new_phi_0_i_mid2_reg_927_pp0_iter4_reg[0:0] == 1'b1) ? sum_1_fu_640_p2 : sum_mid2_fu_605_p3);

assign sum_3_fu_652_p3 = ((cmp6_new_phi_0_i_mid2_reg_927_pp0_iter4_reg[0:0] == 1'b1) ? sum_1_fu_640_p2 : add_new_phi_0_i_fu_74);

assign sum_4_fu_659_p2 = (mul_ln13_1_reg_1005 + sum_2_fu_645_p3);

assign sum_5_fu_664_p3 = ((icmp_ln11_reg_961_pp0_iter4_reg[0:0] == 1'b1) ? sum_4_fu_659_p2 : sum_2_fu_645_p3);

assign sum_mid2_fu_605_p3 = ((or_ln22_1_reg_918_pp0_iter4_reg[0:0] == 1'b1) ? select_ln22_6_fu_598_p3 : 32'd0);

assign tmp_1_fu_451_p3 = k_1_mid2_fu_363_p3[32'd1];

assign tmp_5_fu_482_p3 = {{tmp_1_fu_451_p3}, {2'd2}};

assign tmp_fu_395_p3 = {{trunc_ln13_fu_391_p1}, {2'd0}};

assign trunc_ln13_fu_391_p1 = select_ln8_fu_350_p3[0:0];

assign zext_ln13_1_fu_429_p1 = add_ln13_fu_423_p2;

assign zext_ln13_2_fu_446_p1 = add_ln13_1_fu_440_p2;

assign zext_ln13_3_fu_467_p1 = or_ln_fu_459_p3;

assign zext_ln13_4_fu_477_p1 = add_ln13_2_fu_471_p2;

assign zext_ln13_5_fu_496_p1 = add_ln13_3_fu_490_p2;

assign zext_ln13_fu_403_p1 = select_ln8_fu_350_p3;

endmodule //attention_attention_Pipeline_VITIS_LOOP_8_1_VITIS_LOOP_9_2_VITIS_LOOP_11_3
